version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      codeql:
        patterns:
          - github/codeql-action/*
    open-pull-requests-limit: 10
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    groups:
      python-quality:
        patterns:
          - ruff
          - mypy
          - coverage
    open-pull-requests-limit: 10
