from __future__ import annotations

import os
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from agent_lifecycle.compiler import compile_task_packets  # noqa: E402
from agent_lifecycle.contracts import LifecycleError, canonical_digest, write_json_create  # noqa: E402
from agent_lifecycle.contracts.authority_io import create_authority_bytes  # noqa: E402


class TaskPacketCompilerTests(unittest.TestCase):
    def test_safe_standard_and_compact_bytes_match_release_2_14(self) -> None:
        import hashlib
        import shutil

        from agent_lifecycle.compiler import compile_small_model_packets
        from agent_lifecycle.resources import builtin_profile_path

        # Raw file SHA256 oracles include LF, generated by unchanged v2.14.0
        # source 2706b99b4ec40bdf75ee3df7ac509a339d8620f1 on this frozen fixture.
        golden = [
            {
                "compact": False,
                "explicit": False,
                "files": [
                    (
                        "work/canonical-v2-plan-package/workflow/task-packets/WS-FIXTURE.task-packet.json",
                        "9893c758c55903c027523569a1dff875fbbfca9df024e302983ff38f99db6ff2",
                    ),
                    (
                        "work/canonical-v2-plan-package/workflow/task-packets/index.json",
                        "211e7c652265ba10f3ebbafdacd52d06698584c2d083e9d55c731ec9115582cc",
                    ),
                ],
            },
            {
                "compact": False,
                "explicit": True,
                "files": [
                    (
                        "exports/safe/WS-FIXTURE.task-packet.json",
                        "9893c758c55903c027523569a1dff875fbbfca9df024e302983ff38f99db6ff2",
                    ),
                    ("exports/safe/index.json", "e9d177aed43849bcfd14ff4d9e754c429385d30c8895930c43be23aa8d0b7156"),
                ],
            },
            {
                "compact": True,
                "explicit": False,
                "files": [
                    (
                        "work/canonical-v2-plan-package/workflow/small-model-packets/WS-FIXTURE.small-model-packet.json",
                        "98220ed70d3dee5010e5729779faaef0dcb0ac8012826adf3205786d1826b148",
                    ),
                    (
                        "work/canonical-v2-plan-package/workflow/small-model-packets/index.json",
                        "5667916dcd246449d97197c3ec4392423cdf67b7e3ef949137d70689c71fcb0b",
                    ),
                ],
            },
            {
                "compact": True,
                "explicit": True,
                "files": [
                    (
                        "exports/safe/WS-FIXTURE.small-model-packet.json",
                        "98220ed70d3dee5010e5729779faaef0dcb0ac8012826adf3205786d1826b148",
                    ),
                    ("exports/safe/index.json", "816bf559b846690c6dd77c97ff0d0f9b07aa5ffa563199de12fe3b9db13a0b05"),
                ],
            },
        ]
        fixture = Path("tests/freeze/fixtures/canonical-v2-plan-package")
        for case in golden:
            with self.subTest(compact=case["compact"], explicit=case["explicit"]), tempfile.TemporaryDirectory() as tmp:
                root = Path(tmp)
                shutil.copytree(ROOT / fixture, root / fixture)
                previous_cwd = Path.cwd()
                os.chdir(root)
                try:
                    before = {p.relative_to(root).as_posix() for p in root.rglob("*") if p.is_file()}
                    kwargs = {"out_dir": Path("exports/safe")} if case["explicit"] else {}
                    for _ in range(2):
                        if case["compact"]:
                            compile_small_model_packets(
                                fixture / "plan.manifest.json",
                                context_profile_path=builtin_profile_path("small-context-profile.v1.json"),
                                write=True,
                                **kwargs,
                            )
                        else:
                            compile_task_packets(fixture / "plan.manifest.json", write=True, **kwargs)
                        actual = {
                            p.relative_to(root).as_posix(): hashlib.sha256(p.read_bytes()).hexdigest()
                            for p in root.rglob("*")
                            if p.is_file() and p.relative_to(root).as_posix() not in before
                        }
                        self.assertEqual(actual, dict(case["files"]))
                finally:
                    os.chdir(previous_cwd)

    def test_swapped_ancestor_after_preflight_cannot_redirect_guarded_write(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            previous_cwd = Path.cwd()
            os.chdir(tmp)
            try:
                manifest = _write_bundle(Path(tmp))
                Path("runtime").mkdir()
                probe = Path("link-probe")
                try:
                    probe.symlink_to(Path("runtime").absolute(), target_is_directory=True)
                except OSError as exc:
                    self.skipTest(f"native symlink creation unavailable: {exc}")
                probe.unlink()
                protected = Path("plans/p/.agent-plan/p")
                before = _file_inventory(protected)

                def swapped(path, data, **kwargs):
                    Path("runtime").rmdir()
                    Path("runtime").symlink_to(protected.absolute(), target_is_directory=True)
                    return create_authority_bytes(path, data, **kwargs)

                with (
                    patch("agent_lifecycle.compiler.task_packets.create_authority_bytes", side_effect=swapped),
                    self.assertRaises(LifecycleError) as raised,
                ):
                    compile_task_packets(manifest, out_dir=Path("runtime/new"), write=True)
                self.assertEqual(raised.exception.code, "authority-input-symlink")
                self.assertEqual(_file_inventory(protected), before)
            finally:
                os.chdir(previous_cwd)

    def test_output_conflict_is_rejected_before_any_write(self) -> None:
        for out_dir in ("plans/p/.agent-plan/p", "plans/p/.agent-plan/p/new", "plans/p/plan.manifest.json"):
            with self.subTest(out_dir=out_dir), tempfile.TemporaryDirectory() as tmp:
                previous_cwd = Path.cwd()
                os.chdir(tmp)
                try:
                    manifest = _write_bundle(Path(tmp))
                    before = _file_inventory(Path(tmp))
                    with self.assertRaises(LifecycleError) as raised:
                        compile_task_packets(manifest, out_dir=Path(out_dir), write=True)
                    self.assertEqual(raised.exception.code, "plan-output-conflict")
                    self.assertEqual(_file_inventory(Path(tmp)), before)
                finally:
                    os.chdir(previous_cwd)

    def test_symlink_parent_and_outside_absolute_export_do_not_create_files(self) -> None:
        with tempfile.TemporaryDirectory() as tmp, tempfile.TemporaryDirectory() as outside:
            previous_cwd = Path.cwd()
            os.chdir(tmp)
            try:
                manifest = _write_bundle(Path(tmp))
                with self.assertRaises(LifecycleError) as raised:
                    compile_task_packets(manifest, out_dir=Path(outside) / "no", write=True)
                self.assertEqual(raised.exception.code, "authority-path-outside-root")
                self.assertEqual(list(Path(outside).iterdir()), [])
                try:
                    Path("alias").symlink_to(Path("plans/p/.agent-plan/p").absolute(), target_is_directory=True)
                except OSError as exc:
                    self.skipTest(f"native symlink creation unavailable: {exc}")
                before = _file_inventory(Path(tmp))
                with self.assertRaises(LifecycleError) as raised:
                    compile_task_packets(manifest, out_dir=Path("alias/missing/child"), write=True)
                self.assertEqual(raised.exception.code, "authority-input-symlink")
                self.assertEqual(_file_inventory(Path(tmp)), before)
            finally:
                os.chdir(previous_cwd)

    def test_all_task_filenames_checked_before_first_packet_write(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            previous_cwd = Path.cwd()
            os.chdir(tmp)
            try:
                value = _manifest()
                value["workstreams"].append({"id": "../late", "writes": []})
                manifest = _write_bundle(Path(tmp), manifest=value)
                with self.assertRaises(LifecycleError):
                    compile_task_packets(manifest, out_dir=Path("new/packets"), write=True)
                self.assertFalse(Path("new").exists())
            finally:
                os.chdir(previous_cwd)

    def test_safe_absolute_export_and_prefix_sibling_preserve_legacy_layout(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            previous_cwd = Path.cwd()
            os.chdir(tmp)
            try:
                manifest = _write_bundle(Path(tmp))
                destination = Path.cwd() / "plans/p/.agent-plan/p-other"
                payload = compile_task_packets(manifest, out_dir=destination, write=True)
                self.assertEqual(payload, compile_task_packets(manifest, out_dir=destination, write=True))
                self.assertTrue((destination / "WS-01.task-packet.json").is_file())
                self.assertFalse(Path("plans/p/workflow/task-packets").exists())
            finally:
                os.chdir(previous_cwd)

    def test_compile_requires_frozen_lock_and_writes_idempotent_packets(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            previous_cwd = Path.cwd()
            os.chdir(tmp)
            try:
                manifest = _write_bundle(Path(tmp))
                payload = compile_task_packets(manifest, write=True)
                repeat = compile_task_packets(manifest, write=True)
            finally:
                os.chdir(previous_cwd)
            self.assertEqual(payload, repeat)
            self.assertEqual(payload["index"]["packetCount"], 1)
            self.assertEqual(payload["index"]["outputDirectory"], "plans/p/workflow/task-packets")
            self.assertEqual(
                payload["index"]["packets"][0]["path"],
                "plans/p/workflow/task-packets/WS-01.task-packet.json",
            )
            self.assertEqual(payload["packets"][0]["task"]["id"], "WS-01")
            self.assertEqual(payload["packets"][0]["acceptance"], [{"id": "AC-1", "evidenceIds": ["EV-1"]}])
            self.assertEqual(payload["packets"][0]["modelRoute"]["modelClass"], "standard-code")

    def test_compile_projects_nested_acceptance_criteria(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            previous_cwd = Path.cwd()
            os.chdir(tmp)
            try:
                manifest = _write_bundle(Path(tmp), nested_acceptance=True)
                payload = compile_task_packets(manifest, write=False)
            finally:
                os.chdir(previous_cwd)
            self.assertEqual(payload["packets"][0]["acceptance"], [{"id": "AC-1", "evidenceIds": ["EV-1"]}])


def _file_inventory(root: Path) -> dict[str, bytes | None]:
    return {
        str(path.relative_to(root)): path.read_bytes() if path.is_file() else None
        for path in root.rglob("*")
        if not path.is_symlink()
    }


def _write_bundle(root: Path, *, nested_acceptance: bool = False, manifest: dict | None = None) -> Path:
    manifest = manifest if manifest is not None else _manifest(nested_acceptance=nested_acceptance)
    digest = canonical_digest(manifest)
    write_json_create(
        root / "plans/p/.agent-plan/p/plan.lock.json",
        {"schemaVersion": "agent-plan-lock.v1", "manifestHash": digest, "planRevision": 1},
    )
    path = root / "plans/p/plan.manifest.json"
    write_json_create(path, manifest)
    return path


def _manifest(*, nested_acceptance: bool = False) -> dict:
    manifest = {
        "status": "FROZEN",
        "planRevision": 1,
        "package": {
            "id": "p",
            "artifactRoot": "plans/p",
            "planArtifactRoot": "plans/p/.agent-plan/p",
        },
        "specification": {"tier": "S1", "revision": 1, "artifact": "spec.json"},
        "readOnly": [],
        "forbiddenWrites": [],
        "leadOwned": [],
        "workstreams": [
            {
                "id": "WS-01",
                "title": "Compile",
                "owner": "worker",
                "reviewer": "reviewer",
                "dependsOn": [],
                "writes": ["src"],
                "plannedItems": [{"id": "REQ-1", "description": "Do it"}],
                "acceptanceIds": ["AC-1"],
                "evidenceIds": ["EV-1"],
                "artifactPaths": {
                    "result": "work/WS-01/attempt-{attempt}/task-result.json",
                    "review": "work/WS-01/attempt-{attempt}/task-review.json",
                },
                "modelRoute": {
                    "schemaVersion": "agent-lifecycle-model-route-decision.v1",
                    "operationId": "route-WS-01",
                    "modelClass": "standard-code",
                    "decisionDigest": "4" * 64,
                },
            }
        ],
    }
    if nested_acceptance:
        manifest["acceptance"] = {"criteria": [{"id": "AC-1", "evidenceIds": ["EV-1"]}]}
    else:
        manifest["acceptanceCriteria"] = [{"id": "AC-1", "evidenceIds": ["EV-1"]}]
    return manifest


class ExplicitOperationRootTests(unittest.TestCase):
    def test_standard_and_compact_writers_ignore_unrelated_cwd(self) -> None:
        import shutil
        from unittest.mock import patch

        from agent_lifecycle.compiler.small_model_packets import compile_small_model_packets
        from agent_lifecycle.compiler.task_packets import compile_task_packets
        from agent_lifecycle.resources import builtin_profile_path

        fixture = Path("tests/freeze/fixtures/canonical-v2-plan-package")
        repository = Path(__file__).resolve().parents[2]
        for compact in (False, True):
            with (
                self.subTest(compact=compact),
                tempfile.TemporaryDirectory() as tmp,
                tempfile.TemporaryDirectory() as other,
            ):
                root = Path(tmp)
                shutil.copytree(repository / fixture, root / fixture)
                with patch("pathlib.Path.cwd", return_value=Path(other)):
                    if compact:
                        compile_small_model_packets(
                            fixture / "plan.manifest.json",
                            repository_root=root,
                            write=True,
                            context_profile_path=builtin_profile_path("small-context-profile.v1.json"),
                        )
                    else:
                        compile_task_packets(fixture / "plan.manifest.json", repository_root=root, write=True)
                suffix = "*.small-model-packet.json" if compact else "*.task-packet.json"
                self.assertTrue(list(root.rglob(suffix)))
                self.assertEqual(list(Path(other).iterdir()), [])


if __name__ == "__main__":
    unittest.main()
