"""Built-in JSON schema definitions for adapter task intake."""

from __future__ import annotations

from typing import Any

from agent_lifecycle.contracts.schema_builders import open_object_schema as _open_object_schema

ADAPTER_TASK_SCHEMAS: dict[str, dict[str, Any]] = {
    "agent-adapter-task-start-receipt.v1": _open_object_schema(
        "agent-adapter-task-start-receipt.v1",
        required=[
            "schemaVersion",
            "status",
            "adapterId",
            "input",
            "action",
            "detectedTaskShape",
            "recommendedQualityProfiles",
            "preImplementationAnalysis",
            "executionStarted",
            "lifecycleCoverageClaimed",
            "requiresReview",
            "auditRequired",
            "freezeBlocked",
            "reviewBlockers",
            "planningImport",
            "adapterSessionReceipt",
            "modelCallsStarted",
            "hostLaunchStarted",
            "secretsWritten",
            "nativeConfigWritten",
            "rawTaskTextStored",
            "productionPromotionClaimed",
            "receiptDigest",
        ],
        properties={
            "status": {"enum": ["REVIEW_REQUIRED", "READY", "BLOCKED"]},
            "adapterId": {"type": "string", "minLength": 1},
            "input": {"type": "object"},
            "action": {"enum": ["DRAFT_INTAKE", "DRAFT_PLAN_REVIEW", "MANAGED_RUN", "BLOCKED"]},
            "detectedTaskShape": {"enum": ["bugfix", "analysis-first", "feature", "unknown"]},
            "recommendedQualityProfiles": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "preImplementationAnalysis": {"type": "object"},
            "executionStarted": {"type": "boolean"},
            "lifecycleCoverageClaimed": {"type": "boolean"},
            "requiresReview": {"type": "boolean"},
            "auditRequired": {"type": "boolean"},
            "freezeBlocked": {"type": "boolean"},
            "reviewBlockers": {"type": "array", "items": {"type": "object"}},
            "planningImport": {"type": ["object", "null"]},
            "adapterSessionReceipt": {"type": ["object", "null"]},
            "reviewMeshRecommendation": {"type": ["object", "null"]},
            "modelCallsStarted": {"const": False},
            "hostLaunchStarted": {"type": "boolean"},
            "secretsWritten": {"const": False},
            "nativeConfigWritten": {"const": False},
            "rawTaskTextStored": {"const": False},
            "productionPromotionClaimed": {"const": False},
            "receiptDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-adapter-task-run-request.v1": _open_object_schema(
        "agent-adapter-task-run-request.v1",
        required=[
            "schemaVersion",
            "state",
            "manifest",
            "task",
            "operationId",
            "expectedRevision",
            "sourceRevision",
        ],
        properties={
            "adapterId": {"type": "string", "minLength": 1},
            "adapter": {"type": "string", "minLength": 1},
            "state": {"type": "string", "minLength": 1},
            "manifest": {"type": "string", "minLength": 1},
            "lock": {"type": "string", "minLength": 1},
            "task": {"type": "string", "minLength": 1},
            "operationId": {"type": "string", "minLength": 1},
            "expectedRevision": {"type": "integer", "minimum": 1},
            "sourceRevision": {"type": "string", "minLength": 1},
            "executionAuthorized": {"type": "boolean"},
            "lifecycleCoverageRequired": {"type": "boolean"},
            "requestDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "productionPromotionClaimed": {"const": False},
        },
    ),
}
