"""Built-in JSON schema definitions for managed adapter sessions."""

from __future__ import annotations

from typing import Any

from agent_lifecycle.contracts.schema_builders import open_object_schema as _open_object_schema

ADAPTER_SESSION_SCHEMAS: dict[str, dict[str, Any]] = {
    "agent-adapter-session-receipt.v1": _open_object_schema(
        "agent-adapter-session-receipt.v1",
        required=[
            "schemaVersion",
            "status",
            "sessionId",
            "adapterId",
            "mode",
            "managedWorkflow",
            "lifecycleCoverageClaimed",
            "launchProfile",
            "stateIdentity",
            "managedWorkflowProof",
            "progressHookDefault",
            "hostLaunchStarted",
            "modelCallsStarted",
            "stateWritten",
            "secretsWritten",
            "nativeConfigWritten",
            "productionPromotionClaimed",
            "receiptDigest",
        ],
        properties={
            "status": {"enum": ["WAITING_FOR_TASK", "READY", "LAUNCHED", "BLOCKED", "UNMANAGED", "PASS"]},
            "sessionId": {"type": "string", "minLength": 1},
            "adapterId": {"type": "string", "minLength": 1},
            "mode": {"enum": ["INTERACTIVE", "MANAGED_TASK", "RESUME", "PROMOTED"]},
            "managedWorkflow": {"type": "boolean"},
            "lifecycleCoverageClaimed": {"type": "boolean"},
            "launchProfile": {"type": "object"},
            "stateIdentity": {"type": ["object", "null"]},
            "managedWorkflowProof": {"type": ["object", "null"]},
            "progressHookDefault": {"enum": ["off", "stderr", "receipt"]},
            "hostLaunchStarted": {"type": "boolean"},
            "modelCallsStarted": {"const": False},
            "stateWritten": {"type": "boolean"},
            "secretsWritten": {"const": False},
            "nativeConfigWritten": {"const": False},
            "productionPromotionClaimed": {"const": False},
            "receiptDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-managed-adapter-launch-receipt.v1": _open_object_schema(
        "agent-managed-adapter-launch-receipt.v1",
        required=[
            "schemaVersion",
            "status",
            "adapterId",
            "sessionId",
            "launchMode",
            "argv",
            "shell",
            "timeoutSeconds",
            "env",
            "exitCode",
            "timedOut",
            "cancelled",
            "stdout",
            "stderr",
            "hostLaunchStarted",
            "modelCallsStarted",
            "secretsWritten",
            "nativeConfigWritten",
            "blockers",
            "productionPromotionClaimed",
            "receiptDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL", "BLOCKED"]},
            "adapterId": {"type": "string", "minLength": 1},
            "sessionId": {"type": "string", "minLength": 1},
            "launchMode": {"enum": ["interactive", "managedTask", "resume"]},
            "argv": {"type": "array", "items": {"type": "string"}},
            "shell": {"const": False},
            "timeoutSeconds": {"type": "number"},
            "env": {"type": "object"},
            "exitCode": {"type": ["integer", "null"]},
            "timedOut": {"type": "boolean"},
            "cancelled": {"type": "boolean"},
            "stdout": {"type": "object"},
            "stderr": {"type": "object"},
            "hostLaunchStarted": {"type": "boolean"},
            "modelCallsStarted": {"const": False},
            "secretsWritten": {"const": False},
            "nativeConfigWritten": {"const": False},
            "blockers": {"type": "array"},
            "productionPromotionClaimed": {"const": False},
            "receiptDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-adapter-session-resume-receipt.v1": _open_object_schema(
        "agent-adapter-session-resume-receipt.v1",
        required=[
            "schemaVersion",
            "status",
            "sessionId",
            "adapterId",
            "lineageStatus",
            "expectedIdentity",
            "actualIdentity",
            "managedWorkflow",
            "lifecycleCoverageClaimed",
            "blockers",
            "productionPromotionClaimed",
            "receiptDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "BLOCKED", "UNMANAGED"]},
            "sessionId": {"type": "string", "minLength": 1},
            "adapterId": {"type": "string", "minLength": 1},
            "lineageStatus": {"enum": ["PASS", "FAIL", "NOT_BOUND"]},
            "expectedIdentity": {"type": "object"},
            "actualIdentity": {"type": "object"},
            "managedWorkflow": {"type": "boolean"},
            "lifecycleCoverageClaimed": {"type": "boolean"},
            "blockers": {"type": "array"},
            "productionPromotionClaimed": {"const": False},
            "receiptDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
}
