"""Built-in JSON schemas for bug-forensics contracts."""

from __future__ import annotations

from typing import Any

from agent_lifecycle.contracts.schema_builders import open_object_schema

BUG_FORENSICS_SCHEMAS: dict[str, dict[str, Any]] = {
    "agent-bug-forensics-profile.v1": open_object_schema(
        "agent-bug-forensics-profile.v1",
        required=[
            "schemaVersion",
            "profileId",
            "status",
            "enabledByDefault",
            "activationMode",
            "evidenceChain",
            "phase1Required",
            "phase2Deferred",
            "contextBudget",
            "fixImpactAuthority",
            "crossCheckPolicy",
            "productionPromotionClaimed",
            "profileDigest",
        ],
        properties={
            "profileId": {"const": "bug-forensics"},
            "status": {"const": "OPTIONAL"},
            "enabledByDefault": {"const": False},
            "activationMode": {"const": "explicit-task-trigger"},
            "evidenceChain": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "phase1Required": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "phase2Deferred": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "contextBudget": {"type": "object"},
            "fixImpactAuthority": {"type": "object"},
            "crossCheckPolicy": {"type": "object"},
            "productionPromotionClaimed": {"const": False},
            "profileDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-bug-forensics-profile-validation.v1": open_object_schema(
        "agent-bug-forensics-profile-validation.v1",
        required=["schemaVersion", "status", "profileId", "blockers", "profileDigest", "validationDigest"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "profileId": {"type": ["string", "null"]},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "profileDigest": {"type": ["string", "null"], "minLength": 64, "maxLength": 64},
            "validationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-bug-reproduction-receipt.v1": open_object_schema(
        "agent-bug-reproduction-receipt.v1",
        required=[
            "schemaVersion",
            "status",
            "lineage",
            "symptom",
            "reproductionCommand",
            "commandStatus",
            "beforeModification",
            "artifactDigests",
            "evidenceIds",
            "liveCallsStarted",
            "productionPromotionClaimed",
            "receiptDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL", "INCONCLUSIVE"]},
            "lineage": {"type": "object"},
            "symptom": {"type": "object"},
            "reproductionCommand": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "commandStatus": {"enum": ["FAIL", "ERROR", "PASS", "NOT_RUN", "INCONCLUSIVE"]},
            "beforeModification": {"const": True},
            "artifactDigests": {"type": "array", "items": {"type": "object"}},
            "evidenceIds": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "liveCallsStarted": {"const": False},
            "productionPromotionClaimed": {"const": False},
            "receiptDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-bug-reproduction-receipt-validation.v1": open_object_schema(
        "agent-bug-reproduction-receipt-validation.v1",
        required=["schemaVersion", "status", "receiptStatus", "blockers", "receiptDigest", "validationDigest"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "receiptStatus": {"type": ["string", "null"]},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "receiptDigest": {"type": ["string", "null"], "minLength": 64, "maxLength": 64},
            "validationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-failure-fingerprint.v1": open_object_schema(
        "agent-failure-fingerprint.v1",
        required=[
            "schemaVersion",
            "status",
            "failure",
            "fingerprintFields",
            "affectedSymbols",
            "evidenceIds",
            "productionPromotionClaimed",
            "fingerprintDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL", "INCONCLUSIVE"]},
            "failure": {"type": "object"},
            "fingerprintFields": {"type": "object"},
            "affectedSymbols": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "findingId": {"type": ["string", "null"]},
            "rootCauseDigest": {"type": ["string", "null"], "minLength": 64, "maxLength": 64},
            "evidenceIds": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "productionPromotionClaimed": {"const": False},
            "fingerprintDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-failure-fingerprint-validation.v1": open_object_schema(
        "agent-failure-fingerprint-validation.v1",
        required=["schemaVersion", "status", "blockers", "fingerprintDigest", "validationDigest"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "fingerprintDigest": {"type": ["string", "null"], "minLength": 64, "maxLength": 64},
            "validationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-bug-hypothesis-ledger.v1": open_object_schema(
        "agent-bug-hypothesis-ledger.v1",
        required=[
            "schemaVersion",
            "status",
            "lineage",
            "hypotheses",
            "minimalPatch",
            "evidenceIds",
            "phase2Deferred",
            "productionPromotionClaimed",
            "ledgerDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL", "INCONCLUSIVE"]},
            "lineage": {"type": "object"},
            "hypotheses": {"type": "array", "items": {"type": "object"}},
            "minimalPatch": {"type": "object"},
            "evidenceIds": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "phase2Deferred": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "productionPromotionClaimed": {"const": False},
            "ledgerDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-bug-hypothesis-ledger-validation.v1": open_object_schema(
        "agent-bug-hypothesis-ledger-validation.v1",
        required=["schemaVersion", "status", "ledgerStatus", "blockers", "ledgerDigest", "validationDigest"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "ledgerStatus": {"type": ["string", "null"]},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "ledgerDigest": {"type": ["string", "null"], "minLength": 64, "maxLength": 64},
            "validationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-regression-proof-receipt.v1": open_object_schema(
        "agent-regression-proof-receipt.v1",
        required=[
            "schemaVersion",
            "status",
            "lineage",
            "before",
            "after",
            "reproductionReceiptDigest",
            "fixImpact",
            "evidenceIds",
            "productionPromotionClaimed",
            "proofDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL", "INCONCLUSIVE"]},
            "lineage": {"type": "object"},
            "before": {"type": "object"},
            "after": {"type": "object"},
            "reproductionReceiptDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "fixImpact": {"type": "object"},
            "crossCheck": {"type": ["object", "null"]},
            "evidenceIds": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "productionPromotionClaimed": {"const": False},
            "proofDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-regression-proof-receipt-validation.v1": open_object_schema(
        "agent-regression-proof-receipt-validation.v1",
        required=["schemaVersion", "status", "proofStatus", "blockers", "fingerprintDigest", "proofDigest", "validationDigest"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "proofStatus": {"type": ["string", "null"]},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "fingerprintDigest": {"type": ["string", "null"], "minLength": 64, "maxLength": 64},
            "proofDigest": {"type": ["string", "null"], "minLength": 64, "maxLength": 64},
            "validationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-bug-forensics-gate-receipt.v1": open_object_schema(
        "agent-bug-forensics-gate-receipt.v1",
        required=[
            "schemaVersion",
            "status",
            "taskId",
            "profileId",
            "activated",
            "chainVerified",
            "evidence",
            "blockers",
            "phase2Deferred",
            "productionPromotionClaimed",
            "receiptDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL", "SKIPPED"]},
            "taskId": {"type": ["string", "null"]},
            "profileId": {"type": "string", "minLength": 1},
            "activated": {"type": "boolean"},
            "chainVerified": {"type": "boolean"},
            "evidence": {"type": "object"},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "phase2Deferred": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "productionPromotionClaimed": {"const": False},
            "receiptDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-bug-forensics-gate-validation.v1": open_object_schema(
        "agent-bug-forensics-gate-validation.v1",
        required=["schemaVersion", "status", "gateStatus", "blockers", "receiptDigest", "validationDigest"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "gateStatus": {"type": ["string", "null"]},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "receiptDigest": {"type": ["string", "null"], "minLength": 64, "maxLength": 64},
            "validationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-bug-forensics-audit.v1": open_object_schema(
        "agent-bug-forensics-audit.v1",
        required=[
            "schemaVersion",
            "status",
            "taskId",
            "gateReceiptDigest",
            "coverage",
            "blockers",
            "productionPromotionClaimed",
            "auditDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL", "SKIPPED"]},
            "taskId": {"type": ["string", "null"]},
            "gateReceiptDigest": {"type": ["string", "null"], "minLength": 64, "maxLength": 64},
            "coverage": {"type": "object"},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "productionPromotionClaimed": {"const": False},
            "auditDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-bug-forensics-audit-validation.v1": open_object_schema(
        "agent-bug-forensics-audit-validation.v1",
        required=["schemaVersion", "status", "auditStatus", "blockers", "auditDigest", "validationDigest"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "auditStatus": {"type": ["string", "null"]},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "auditDigest": {"type": ["string", "null"], "minLength": 64, "maxLength": 64},
            "validationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-bug-forensics-recipe-library.v1": open_object_schema(
        "agent-bug-forensics-recipe-library.v1",
        required=[
            "schemaVersion",
            "status",
            "profileId",
            "enabledByDefault",
            "activationMode",
            "reusesExistingReceiptSchemas",
            "competingReceiptSchemas",
            "defaultLiveCalls",
            "budgetUnits",
            "contextBudget",
            "profileDigest",
            "recipes",
            "productionPromotionClaimed",
            "libraryDigest",
        ],
        properties={
            "status": {"const": "OPTIONAL"},
            "profileId": {"const": "bug-forensics"},
            "enabledByDefault": {"const": False},
            "activationMode": {"const": "explicit-task-trigger"},
            "reusesExistingReceiptSchemas": {"const": True},
            "competingReceiptSchemas": {"type": "array", "maxItems": 0},
            "defaultLiveCalls": {"const": 0},
            "budgetUnits": {"const": "tokens-and-resources"},
            "contextBudget": {"type": "object"},
            "profileDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "recipes": {"type": "array", "items": {"type": "object"}},
            "productionPromotionClaimed": {"const": False},
            "libraryDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-bug-forensics-recipe-validation.v1": open_object_schema(
        "agent-bug-forensics-recipe-validation.v1",
        required=[
            "schemaVersion",
            "status",
            "profileId",
            "recipeCount",
            "recipeIds",
            "reports",
            "blockers",
            "libraryDigest",
            "productionPromotionClaimed",
            "validationDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "profileId": {"type": ["string", "null"]},
            "recipeCount": {"type": "integer", "minimum": 0},
            "recipeIds": {"type": "array", "items": {"type": "string"}},
            "reports": {"type": "array", "items": {"type": "object"}},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "libraryDigest": {"type": ["string", "null"], "minLength": 64, "maxLength": 64},
            "productionPromotionClaimed": {"const": False},
            "validationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
}
