"""Built-in contracts for bounded context checkpoints."""

from __future__ import annotations

from typing import Any

from agent_lifecycle.contracts.schema_builders import open_object_schema


CHECKPOINT_MODES = ("NATIVE_HOOK", "MILESTONE", "AGENT_REQUESTED", "UNAVAILABLE")


CONTEXT_CHECKPOINT_SCHEMAS: dict[str, dict[str, Any]] = {
    "agent-context-checkpoint.v1": open_object_schema(
        "agent-context-checkpoint.v1",
        required=[
            "schemaVersion",
            "status",
            "checkpointId",
            "sessionId",
            "runId",
            "adapterId",
            "packageId",
            "planRevision",
            "planDigest",
            "stateRevision",
            "sourceRevision",
            "captureMode",
            "supportLevel",
            "reason",
            "summary",
            "referencedArtifacts",
            "captureEvidence",
            "redactionStatus",
            "implementationAuthorized",
            "proofAuthority",
            "createdAt",
            "productionPromotionClaimed",
            "checkpointDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "REVIEW_REQUIRED", "BLOCKED"]},
            "checkpointId": {"type": "string", "minLength": 1},
            "sessionId": {"type": "string", "minLength": 1},
            "runId": {"type": "string", "minLength": 1},
            "adapterId": {"type": "string", "minLength": 1},
            "packageId": {"type": "string", "minLength": 1},
            "planRevision": {"type": "integer", "minimum": 1},
            "planDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "stateRevision": {"type": "integer", "minimum": 1},
            "sourceRevision": {"type": "string", "minLength": 1},
            "captureMode": {"enum": list(CHECKPOINT_MODES)},
            "supportLevel": {"enum": list(CHECKPOINT_MODES)},
            "reason": {"type": "string", "minLength": 1, "maxLength": 512},
            "summary": {"type": "object"},
            "referencedArtifacts": {"type": "array", "maxItems": 32, "items": {"type": "object"}},
            "captureEvidence": {"type": ["object", "null"]},
            "redactionStatus": {"type": "object"},
            "implementationAuthorized": {"const": False},
            "proofAuthority": {"const": "none"},
            "createdAt": {"type": "string", "minLength": 1},
            "productionPromotionClaimed": {"const": False},
            "checkpointDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-context-checkpoint-validation.v1": open_object_schema(
        "agent-context-checkpoint-validation.v1",
        required=[
            "schemaVersion",
            "status",
            "checkpointId",
            "checks",
            "blockers",
            "productionPromotionClaimed",
            "validationDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "checkpointId": {"type": ["string", "null"]},
            "checks": {"type": "array", "items": {"type": "object"}},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "productionPromotionClaimed": {"const": False},
            "validationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-context-checkpoint-event.v1": open_object_schema(
        "agent-context-checkpoint-event.v1",
        required=[
            "schemaVersion",
            "eventId",
            "eventType",
            "sessionId",
            "runId",
            "operationId",
            "stateRevision",
            "captureMode",
            "checkpointDigest",
            "recordedAt",
            "payload",
            "productionPromotionClaimed",
            "eventDigest",
        ],
        properties={
            "eventId": {"type": "string", "minLength": 1},
            "eventType": {"enum": ["context.checkpoint.created", "context.checkpoint.unavailable"]},
            "sessionId": {"type": "string", "minLength": 1},
            "runId": {"type": "string", "minLength": 1},
            "operationId": {"type": "string", "minLength": 1},
            "stateRevision": {"type": "integer", "minimum": 1},
            "captureMode": {"enum": list(CHECKPOINT_MODES)},
            "checkpointDigest": {"type": ["string", "null"], "minLength": 0, "maxLength": 64},
            "recordedAt": {"type": "string", "minLength": 1},
            "payload": {"type": "object"},
            "productionPromotionClaimed": {"const": False},
            "eventDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-context-checkpoint-event-validation.v1": open_object_schema(
        "agent-context-checkpoint-event-validation.v1",
        required=["schemaVersion", "status", "eventId", "blockers", "productionPromotionClaimed", "validationDigest"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "eventId": {"type": ["string", "null"]},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "productionPromotionClaimed": {"const": False},
            "validationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-context-continuation.v1": open_object_schema(
        "agent-context-continuation.v1",
        required=[
            "schemaVersion",
            "status",
            "checkpointId",
            "checkpointDigest",
            "lineage",
            "captureMode",
            "summary",
            "referencedArtifacts",
            "implementationAuthorized",
            "proofAuthority",
            "contextLimits",
            "validationDigest",
            "productionPromotionClaimed",
            "continuationDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "BLOCKED"]},
            "checkpointId": {"type": "string", "minLength": 1},
            "checkpointDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "lineage": {"type": "object"},
            "captureMode": {"enum": list(CHECKPOINT_MODES)},
            "summary": {"type": "object"},
            "referencedArtifacts": {"type": "array", "maxItems": 32, "items": {"type": "object"}},
            "implementationAuthorized": {"const": False},
            "proofAuthority": {"const": "none"},
            "contextLimits": {"type": "object"},
            "validationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "productionPromotionClaimed": {"const": False},
            "continuationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
}
