"""Built-in JSON schema definitions for a lifecycle contract domain."""

from __future__ import annotations

from typing import Any

from agent_lifecycle.contracts.schema_builders import open_object_schema as _open_object_schema

CORE_SCHEMAS: dict[str, dict[str, Any]] = {
    "agent-lifecycle-version.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "agent-lifecycle-version.v1",
        "type": "object",
        "additionalProperties": False,
        "required": ["schemaVersion", "version"],
        "properties": {
            "schemaVersion": {"const": "agent-lifecycle-version.v1"},
            "version": {"type": "string", "minLength": 1},
        },
    },
    "agent-lifecycle-schema-index.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "agent-lifecycle-schema-index.v1",
        "type": "object",
        "additionalProperties": False,
        "required": ["schemaVersion", "schemas"],
        "properties": {
            "schemaVersion": {"const": "agent-lifecycle-schema-index.v1"},
            "schemas": {"type": "array", "items": {"type": "object"}},
        },
    },
    "agent-lifecycle-error.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "agent-lifecycle-error.v1",
        "type": "object",
        "additionalProperties": False,
        "required": ["schemaVersion", "code", "message", "details"],
        "properties": {
            "schemaVersion": {"const": "agent-lifecycle-error.v1"},
            "code": {"type": "string", "minLength": 1},
            "message": {"type": "string", "minLength": 1},
            "details": {"type": "object"},
        },
    },
    "agent-host-operation-request.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "agent-host-operation-request.v1",
        "type": "object",
        "additionalProperties": False,
        "required": [
            "schemaVersion",
            "operationId",
            "capability",
            "inputs",
            "outputs",
            "constraints",
        ],
        "properties": {
            "schemaVersion": {"const": "agent-host-operation-request.v1"},
            "operationId": {"type": "string", "minLength": 1},
            "capability": {"type": "string", "minLength": 1},
            "inputs": {"type": "object"},
            "outputs": {"type": "array", "items": {"type": "object"}},
            "constraints": {"type": "object"},
            "modelRoute": {"type": "object"},
        },
    },
    "agent-host-operation-receipt.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "agent-host-operation-receipt.v1",
        "type": "object",
        "additionalProperties": False,
        "required": [
            "schemaVersion",
            "operationId",
            "capability",
            "status",
            "outputs",
            "usage",
        ],
        "properties": {
            "schemaVersion": {"const": "agent-host-operation-receipt.v1"},
            "operationId": {"type": "string", "minLength": 1},
            "capability": {"type": "string", "minLength": 1},
            "status": {"enum": ["PASS", "FAIL", "BLOCKED"]},
            "outputs": {"type": "array", "items": {"type": "object"}},
            "usage": {"type": "object"},
        },
    },
    "agent-small-model-task-packet.v1": _open_object_schema(
        "agent-small-model-task-packet.v1",
        required=[
            "schemaVersion",
            "plan",
            "task",
            "executionSurface",
            "sourceTaskPacketDigest",
            "writeScope",
            "requiredOutputContract",
            "validation",
            "context",
            "adaptivePolicy",
            "forbiddenActions",
            "compactInstructions",
            "productionPromotionClaimed",
            "packetDigest",
        ],
        properties={
            "plan": {"type": "object"},
            "task": {"type": "object"},
            "executionSurface": {"const": "small-model"},
            "sourceTaskPacketDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "writeScope": {"type": "object"},
            "requiredOutputContract": {"type": "object"},
            "validation": {"type": "object"},
            "context": {"type": "object"},
            "adaptivePolicy": {"type": "object"},
            "forbiddenActions": {"type": "array", "items": {"type": "string"}},
            "compactInstructions": {"type": "object"},
            "productionPromotionClaimed": {"const": False},
            "packetDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-small-model-task-packet-index.v1": _open_object_schema(
        "agent-small-model-task-packet-index.v1",
        required=[
            "schemaVersion",
            "status",
            "packageId",
            "manifestDigest",
            "sourcePacketSetHash",
            "outputDirectory",
            "targetWindow",
            "packetCount",
            "packets",
            "adaptivePolicy",
            "blockers",
            "productionPromotionClaimed",
            "indexDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "packageId": {"type": ["string", "null"]},
            "manifestDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "sourcePacketSetHash": {"type": "string", "minLength": 64, "maxLength": 64},
            "outputDirectory": {"type": "string"},
            "targetWindow": {"enum": ["4k-strict", "8k", "16k"]},
            "packetCount": {"type": "integer", "minimum": 0},
            "packets": {"type": "array", "items": {"type": "object"}},
            "adaptivePolicy": {"type": "object"},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "productionPromotionClaimed": {"const": False},
            "indexDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-small-model-output-contract.v1": _open_object_schema(
        "agent-small-model-output-contract.v1",
        required=[
            "schemaVersion",
            "taskId",
            "requiredSchemaVersion",
            "allowedStatuses",
            "requiredFields",
            "writeScope",
            "writeScopeDigest",
            "validation",
            "productionPromotionClaimed",
            "contractDigest",
        ],
        properties={
            "taskId": {"type": "string", "minLength": 1},
            "requiredSchemaVersion": {"const": "agent-small-model-task-result.v1"},
            "allowedStatuses": {"type": "array", "items": {"type": "string"}},
            "requiredFields": {"type": "array", "items": {"type": "string"}},
            "writeScope": {"type": "object"},
            "writeScopeDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "validation": {"type": "object"},
            "productionPromotionClaimed": {"const": False},
            "contractDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-small-model-task-result.v1": _open_object_schema(
        "agent-small-model-task-result.v1",
        required=[
            "schemaVersion",
            "status",
            "taskId",
            "changedFiles",
            "validation",
            "summary",
            "blockers",
            "writeScopeDigest",
            "outputContractDigest",
            "productionPromotionClaimed",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL", "BLOCKED"]},
            "taskId": {"type": "string", "minLength": 1},
            "changedFiles": {"type": "array", "items": {"type": "string"}},
            "validation": {"type": "array", "items": {"type": "object"}},
            "summary": {"type": "string", "minLength": 1},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "writeScopeDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "outputContractDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "productionPromotionClaimed": {"const": False},
        },
    ),
    "agent-small-model-output-validation.v1": _open_object_schema(
        "agent-small-model-output-validation.v1",
        required=[
            "schemaVersion",
            "status",
            "taskId",
            "changedFiles",
            "blockers",
            "outputDigest",
            "contractDigest",
            "productionPromotionClaimed",
            "validationDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "taskId": {"type": ["string", "null"]},
            "changedFiles": {"type": "array", "items": {"type": "string"}},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "outputDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "contractDigest": {"type": ["string", "null"], "minLength": 64, "maxLength": 64},
            "productionPromotionClaimed": {"const": False},
            "validationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-small-model-packet-compile-result.v1": _open_object_schema(
        "agent-small-model-packet-compile-result.v1",
        required=[
            "schemaVersion",
            "status",
            "index",
            "packets",
            "blockers",
            "productionPromotionClaimed",
            "resultDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "index": {"type": "object"},
            "packets": {"type": "array", "items": {"type": "object"}},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "productionPromotionClaimed": {"const": False},
            "resultDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
}
