"""JSON schema definitions for lifecycle metrics contracts."""

from __future__ import annotations

from typing import Any

from agent_lifecycle.contracts.schema_builders import open_object_schema

METRIC_SCHEMAS: dict[str, dict[str, Any]] = {
    "agent-lifecycle-cost-report.v1": open_object_schema(
        "agent-lifecycle-cost-report.v1",
        required=["schemaVersion", "mode", "entries"],
        properties={
            "mode": {"enum": ["light", "standard", "strict", "release"]},
            "entries": {"type": "array", "items": {"type": "object"}},
            "generatedBy": {"type": "string"},
            "sourceArtifacts": {"type": "array", "items": {"type": "object"}},
            "lineage": {"type": "object"},
            "usageConfidence": {"type": "object"},
            "compactSummary": {"type": "object"},
            "limits": {"type": "object"},
            "overLimitReason": {"type": "string"},
            "productionPromotionClaimed": {"const": False},
        },
    ),
    "agent-lifecycle-cost-validation.v1": open_object_schema(
        "agent-lifecycle-cost-validation.v1",
        required=["schemaVersion", "status", "mode", "totals", "ratios", "limits", "blockers", "reportDigest"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "mode": {"type": ["string", "null"]},
            "totals": {"type": "object"},
            "ratios": {"type": "object"},
            "usageConfidence": {"type": "object"},
            "limits": {"type": "object"},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "reportDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-lifecycle-cost-generation.v1": open_object_schema(
        "agent-lifecycle-cost-generation.v1",
        required=["schemaVersion", "status", "reportPath", "reportDigest", "validation"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "reportPath": {"type": "string"},
            "reportBytes": {"type": "integer", "minimum": 0},
            "reportDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "summaryPath": {"type": ["string", "null"]},
            "summaryDigest": {"type": ["string", "null"]},
            "validation": {"type": "object"},
            "liveCallsStarted": {"const": False},
            "productionPromotionClaimed": {"const": False},
        },
    ),
    "agent-lifecycle-cost-summary.v1": open_object_schema(
        "agent-lifecycle-cost-summary.v1",
        required=[
            "schemaVersion",
            "mode",
            "latestUserIntent",
            "activeDecisions",
            "openBlockers",
            "acceptedEvidence",
            "changedFiles",
            "nextRequiredAction",
            "doNotDo",
            "categoryTotals",
            "ratios",
            "usageConfidence",
        ],
        properties={
            "mode": {"type": ["string", "null"]},
            "activeDecisions": {"type": "array", "items": {"type": "string"}},
            "openBlockers": {"type": "array"},
            "acceptedEvidence": {"type": "array", "items": {"type": "object"}},
            "changedFiles": {"type": "array", "items": {"type": "string"}},
            "nextRequiredAction": {"type": "string"},
            "doNotDo": {"type": "array", "items": {"type": "string"}},
            "categoryTotals": {"type": "object"},
            "ratios": {"type": "object"},
            "usageConfidence": {"type": "object"},
            "usefulWorkTokens": {"type": "integer", "minimum": 0},
            "processOverheadTokens": {"type": "integer", "minimum": 0},
        },
    ),
    "agent-lifecycle-baselines.v1": open_object_schema(
        "agent-lifecycle-baselines.v1",
        required=["schemaVersion", "profileId", "minimumReportsForConfidence", "taskShapes", "riskFloors"],
        properties={
            "profileId": {"type": "string", "minLength": 1},
            "minimumReportsForConfidence": {"type": "integer", "minimum": 1},
            "modeOrder": {"type": "array", "items": {"type": "string"}},
            "taskShapes": {"type": "object"},
            "riskFloors": {"type": "object"},
            "productionPromotionClaimed": {"const": False},
        },
    ),
    "agent-lifecycle-baselines-validation.v1": open_object_schema(
        "agent-lifecycle-baselines-validation.v1",
        required=["schemaVersion", "status", "taskShapeCount", "blockers", "profileDigest", "validationDigest"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "taskShapeCount": {"type": "integer", "minimum": 0},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "profileDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "validationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-lifecycle-overhead-statistics.v1": open_object_schema(
        "agent-lifecycle-overhead-statistics.v1",
        required=["schemaVersion", "status", "reportCount", "totals", "ratios", "usageConfidence", "blockers"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "reportCount": {"type": "integer", "minimum": 0},
            "reportDigests": {"type": "array", "items": {"type": "string"}},
            "totals": {"type": "object"},
            "ratios": {"type": "object"},
            "usageConfidence": {"type": "object"},
            "averageProductValidationSteps": {"type": "number", "minimum": 0},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "statisticsDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-lifecycle-recommendation.v1": open_object_schema(
        "agent-lifecycle-recommendation.v1",
        required=[
            "schemaVersion",
            "status",
            "taskShape",
            "recommendedMode",
            "confidence",
            "advisoryOnly",
            "autoApply",
            "qualityFloorPreserved",
            "warnings",
            "reasons",
            "statistics",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "taskShape": {"type": "string", "minLength": 1},
            "currentMode": {"type": ["string", "null"]},
            "recommendedMode": {"enum": ["light", "standard", "strict", "release"]},
            "confidence": {"enum": ["LOW", "MEDIUM", "HIGH"]},
            "advisoryOnly": {"const": True},
            "autoApply": {"const": False},
            "qualityFloor": {"enum": ["light", "standard", "strict", "release"]},
            "qualityFloorPreserved": {"const": True},
            "warnings": {"type": "array", "items": {"type": "object"}},
            "reasons": {"type": "array", "items": {"type": "string"}},
            "statistics": {"type": "object"},
            "baselineValidation": {"type": "object"},
            "compactSummary": {"type": "object"},
            "productionPromotionClaimed": {"const": False},
            "recommendationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-lifecycle-recommendation-summary.v1": open_object_schema(
        "agent-lifecycle-recommendation-summary.v1",
        required=[
            "schemaVersion",
            "latestUserIntent",
            "activeDecisions",
            "openBlockers",
            "acceptedEvidence",
            "changedFiles",
            "nextRequiredAction",
            "doNotDo",
            "recommendedMode",
            "confidence",
            "qualityFloorPreserved",
        ],
        properties={
            "activeDecisions": {"type": "array", "items": {"type": "string"}},
            "openBlockers": {"type": "array"},
            "acceptedEvidence": {"type": "array", "items": {"type": "object"}},
            "changedFiles": {"type": "array", "items": {"type": "string"}},
            "nextRequiredAction": {"type": "string"},
            "doNotDo": {"type": "array", "items": {"type": "string"}},
            "recommendedMode": {"enum": ["light", "standard", "strict", "release"]},
            "confidence": {"enum": ["LOW", "MEDIUM", "HIGH"]},
            "warnings": {"type": "array", "items": {"type": "object"}},
            "qualityFloorPreserved": {"const": True},
        },
    ),
    "agent-phase-resource-measurement.v1": open_object_schema(
        "agent-phase-resource-measurement.v1",
        required=[
            "schemaVersion",
            "status",
            "phaseCount",
            "phases",
            "usageExport",
            "totals",
            "blockers",
            "productionPromotionClaimed",
            "measurementDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "phaseCount": {"type": "integer", "minimum": 1},
            "phases": {"type": "array", "items": {"type": "object"}},
            "usageExport": {"type": "object"},
            "totals": {"type": "object"},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "productionPromotionClaimed": {"const": False},
            "measurementDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-phase-resource-measurement-validation.v1": open_object_schema(
        "agent-phase-resource-measurement-validation.v1",
        required=["schemaVersion", "status", "measurementStatus", "phaseCount", "totals", "blockers", "measurementDigest", "validationDigest"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "measurementStatus": {"type": ["string", "null"]},
            "phaseCount": {"type": "integer", "minimum": 0},
            "totals": {"type": "object"},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "measurementDigest": {"type": ["string", "null"], "minLength": 64, "maxLength": 64},
            "validationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
}
