"""JSON schema definitions for lifecycle policy proposal contracts."""

from __future__ import annotations

from typing import Any

from agent_lifecycle.contracts.schema_builders import open_object_schema

POLICY_SCHEMAS: dict[str, dict[str, Any]] = {
    "agent-lifecycle-regression-signals.v1": open_object_schema(
        "agent-lifecycle-regression-signals.v1",
        required=[
            "schemaVersion",
            "status",
            "signalCount",
            "signals",
            "blockingSignals",
            "blockers",
            "productionPromotionClaimed",
        ],
        properties={
            "status": {"enum": ["PASS", "BLOCK", "FAIL"]},
            "signalCount": {"type": "integer", "minimum": 0},
            "signals": {"type": "array", "items": {"type": "object"}},
            "blockingSignals": {"type": "array", "items": {"type": "object"}},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "productionPromotionClaimed": {"const": False},
            "signalsDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-lifecycle-policy-proposal.v1": open_object_schema(
        "agent-lifecycle-policy-proposal.v1",
        required=[
            "schemaVersion",
            "status",
            "proposalId",
            "sourceRecommendationDigest",
            "regressionSignals",
            "advisoryOnly",
            "autoApply",
            "applyAllowed",
            "refusalReasons",
            "candidateChanges",
            "productionPromotionClaimed",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "proposalId": {"type": "string", "minLength": 1},
            "taskShape": {"type": ["string", "null"]},
            "sourceRecommendationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "regressionSignals": {"type": "object"},
            "advisoryOnly": {"const": True},
            "autoApply": {"const": False},
            "applyAllowed": {"type": "boolean"},
            "refusalReasons": {"type": "array", "items": {"type": "object"}},
            "candidateChanges": {"type": "array", "items": {"type": "object"}},
            "expectedBenefit": {"type": "object"},
            "qualityConstraints": {"type": "object"},
            "rollback": {"type": "object"},
            "compactSummary": {"type": "object"},
            "productionPromotionClaimed": {"const": False},
            "proposalDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-lifecycle-policy-summary.v1": open_object_schema(
        "agent-lifecycle-policy-summary.v1",
        required=[
            "schemaVersion",
            "latestUserIntent",
            "activeDecisions",
            "openBlockers",
            "acceptedEvidence",
            "changedFiles",
            "nextRequiredAction",
            "doNotDo",
            "applyAllowed",
            "candidateChanges",
            "qualityConstraints",
        ],
        properties={
            "activeDecisions": {"type": "array", "items": {"type": "string"}},
            "openBlockers": {"type": "array"},
            "acceptedEvidence": {"type": "array", "items": {"type": "object"}},
            "changedFiles": {"type": "array", "items": {"type": "string"}},
            "nextRequiredAction": {"type": "string"},
            "doNotDo": {"type": "array", "items": {"type": "string"}},
            "applyAllowed": {"type": "boolean"},
            "candidateChanges": {"type": "array", "items": {"type": "object"}},
            "qualityConstraints": {"type": "object"},
        },
    ),
    "agent-lifecycle-tuned-policy.v1": open_object_schema(
        "agent-lifecycle-tuned-policy.v1",
        required=[
            "schemaVersion",
            "status",
            "sourceProposalDigest",
            "changes",
            "rollback",
            "qualityConstraints",
            "productionPromotionClaimed",
            "policyDigest",
        ],
        properties={
            "status": {"const": "PASS"},
            "sourceProposalDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "changes": {"type": "array", "items": {"type": "object"}},
            "rollback": {"type": "object"},
            "qualityConstraints": {"type": "object"},
            "productionPromotionClaimed": {"const": False},
            "policyDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-lifecycle-policy-apply-result.v1": open_object_schema(
        "agent-lifecycle-policy-apply-result.v1",
        required=[
            "schemaVersion",
            "status",
            "outputPath",
            "outputDigest",
            "proposalDigest",
            "changed",
            "liveCallsStarted",
            "productionPromotionClaimed",
        ],
        properties={
            "status": {"const": "PASS"},
            "outputPath": {"type": "string"},
            "outputBytes": {"type": "integer", "minimum": 0},
            "outputDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "proposalDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "changed": {"type": "boolean"},
            "liveCallsStarted": {"const": False},
            "productionPromotionClaimed": {"const": False},
            "applyDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-lifecycle-policy-tune-result.v1": open_object_schema(
        "agent-lifecycle-policy-tune-result.v1",
        required=[
            "schemaVersion",
            "status",
            "mode",
            "proposal",
            "proposalDigest",
            "liveCallsStarted",
            "productionPromotionClaimed",
        ],
        properties={
            "status": {"const": "PASS"},
            "mode": {"enum": ["dry-run", "apply"]},
            "proposal": {"type": "object"},
            "proposalDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "applyResult": {"type": ["object", "null"]},
            "applyDigest": {"type": ["string", "null"]},
            "liveCallsStarted": {"const": False},
            "productionPromotionClaimed": {"const": False},
            "resultDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
}
