"""JSON schema definitions for lifecycle policy proposal contracts."""

from __future__ import annotations

from typing import Any

from agent_lifecycle.contracts.schema_builders import open_object_schema

POLICY_SCHEMAS: dict[str, dict[str, Any]] = {
    "agent-lifecycle-quality-floor-decision.v1": open_object_schema(
        "agent-lifecycle-quality-floor-decision.v1",
        required=[
            "schemaVersion",
            "status",
            "taskShape",
            "riskFlags",
            "requiredEvidence",
            "qualityFloor",
            "reasonCodes",
            "blockers",
            "baselineProfileDigest",
            "productionPromotionClaimed",
            "floorDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "taskShape": {"type": "string", "minLength": 1},
            "sddTier": {"type": ["string", "null"]},
            "riskFlags": {"type": "array", "items": {"type": "string"}},
            "requiredEvidence": {"type": "array", "items": {"type": "string"}},
            "minMode": {"type": ["string", "null"]},
            "qualityFloor": {"enum": ["light", "standard", "strict", "release"]},
            "reasonCodes": {"type": "array", "items": {"type": "string"}},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "baselineProfileDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "productionPromotionClaimed": {"const": False},
            "floorDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-adaptive-lifecycle-policy-request.v1": open_object_schema(
        "agent-adaptive-lifecycle-policy-request.v1",
        required=["schemaVersion", "taskShape", "sddTier"],
        properties={
            "requestId": {"type": ["string", "null"]},
            "taskShape": {"type": "string", "minLength": 1},
            "sddTier": {"enum": ["S0", "S1", "S2"]},
            "riskFlags": {
                "oneOf": [
                    {"type": "array", "items": {"type": "string"}},
                    {"type": "object"},
                ]
            },
            "requiredEvidence": {"type": "array", "items": {"type": "string"}},
            "priorAttempts": {"type": "integer", "minimum": 0},
            "contextTokens": {"type": "integer", "minimum": 0},
            "resourceCaps": {"type": "object"},
            "budgetMode": {"enum": ["local", "subscription", "metered"]},
            "currentMode": {"enum": ["light", "standard", "strict", "release", None]},
            "automaticSelectionEnabled": {"type": "boolean"},
        },
    ),
    "agent-adaptive-lifecycle-policy-decision.v1": open_object_schema(
        "agent-adaptive-lifecycle-policy-decision.v1",
        required=[
            "schemaVersion",
            "status",
            "taskShape",
            "sddTier",
            "recommendedMode",
            "selectedMode",
            "qualityFloor",
            "qualityFloorPreserved",
            "automaticSelectionEnabled",
            "applyAutomatically",
            "advisoryOnly",
            "reasonCodes",
            "neutralInputs",
            "resourceBasis",
            "monetaryFieldsUsed",
            "providerModelNamesInCore",
            "blockers",
            "productionPromotionClaimed",
            "decisionDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "requestId": {"type": ["string", "null"]},
            "taskShape": {"type": "string", "minLength": 1},
            "sddTier": {"enum": ["S0", "S1", "S2"]},
            "currentMode": {"type": ["string", "null"]},
            "recommendedMode": {"enum": ["light", "standard", "strict", "release"]},
            "selectedMode": {"enum": ["light", "standard", "strict", "release"]},
            "qualityFloor": {"enum": ["light", "standard", "strict", "release"]},
            "qualityFloorPreserved": {"const": True},
            "automaticSelectionEnabled": {"type": "boolean"},
            "applyAutomatically": {"type": "boolean"},
            "advisoryOnly": {"type": "boolean"},
            "reasonCodes": {"type": "array", "items": {"type": "string"}},
            "neutralInputs": {"type": "object"},
            "resourceBasis": {"const": "tokens-and-resources"},
            "monetaryFieldsUsed": {"const": False},
            "providerModelNamesInCore": {"const": False},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "qualityFloorDecision": {"type": "object"},
            "baselineValidation": {"type": "object"},
            "requestDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "baselineProfileDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "productionPromotionClaimed": {"const": False},
            "decisionDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-adaptive-lifecycle-policy-decision-validation.v1": open_object_schema(
        "agent-adaptive-lifecycle-policy-decision-validation.v1",
        required=[
            "schemaVersion",
            "status",
            "decisionStatus",
            "qualityFloorPreserved",
            "applyAutomatically",
            "advisoryOnly",
            "blockers",
            "decisionDigest",
            "validationDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "decisionStatus": {"type": ["string", "null"]},
            "recommendedMode": {"type": ["string", "null"]},
            "selectedMode": {"type": ["string", "null"]},
            "qualityFloor": {"type": ["string", "null"]},
            "qualityFloorPreserved": {"type": "boolean"},
            "applyAutomatically": {"type": "boolean"},
            "advisoryOnly": {"type": "boolean"},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "decisionDigest": {"type": ["string", "null"], "minLength": 64, "maxLength": 64},
            "validationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-runtime-policy-receipt.v1": open_object_schema(
        "agent-runtime-policy-receipt.v1",
        required=[
            "schemaVersion",
            "status",
            "policyId",
            "action",
            "subject",
            "adapterEvidence",
            "enforcementMode",
            "enforcementClaimed",
            "advisoryOnly",
            "decisionRecordedBeforeExecution",
            "evidenceIds",
            "blockers",
            "productionPromotionClaimed",
            "receiptDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "policyId": {"type": "string", "minLength": 1},
            "action": {"enum": ["ALLOW", "DENY", "ASK"]},
            "subject": {"type": "object"},
            "adapterEvidence": {"type": "object"},
            "enforcementMode": {"enum": ["enforced", "advisory"]},
            "enforcementClaimed": {"type": "boolean"},
            "advisoryOnly": {"type": "boolean"},
            "decisionRecordedBeforeExecution": {"type": "boolean"},
            "evidenceIds": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "productionPromotionClaimed": {"const": False},
            "receiptDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-runtime-policy-receipt-validation.v1": open_object_schema(
        "agent-runtime-policy-receipt-validation.v1",
        required=[
            "schemaVersion",
            "status",
            "receiptStatus",
            "policyId",
            "action",
            "enforcementMode",
            "enforcementClaimed",
            "blockers",
            "receiptDigest",
            "validationDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "receiptStatus": {"type": ["string", "null"]},
            "policyId": {"type": ["string", "null"]},
            "action": {"type": ["string", "null"]},
            "enforcementMode": {"type": ["string", "null"]},
            "enforcementClaimed": {"type": ["boolean", "null"]},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "receiptDigest": {"type": ["string", "null"], "minLength": 64, "maxLength": 64},
            "validationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-lifecycle-regression-signals.v1": open_object_schema(
        "agent-lifecycle-regression-signals.v1",
        required=[
            "schemaVersion",
            "status",
            "signalCount",
            "signals",
            "blockingSignals",
            "blockers",
            "productionPromotionClaimed",
        ],
        properties={
            "status": {"enum": ["PASS", "BLOCK", "FAIL"]},
            "signalCount": {"type": "integer", "minimum": 0},
            "signals": {"type": "array", "items": {"type": "object"}},
            "blockingSignals": {"type": "array", "items": {"type": "object"}},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "productionPromotionClaimed": {"const": False},
            "signalsDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-lifecycle-policy-proposal.v1": open_object_schema(
        "agent-lifecycle-policy-proposal.v1",
        required=[
            "schemaVersion",
            "status",
            "proposalId",
            "sourceRecommendationDigest",
            "regressionSignals",
            "advisoryOnly",
            "autoApply",
            "applyAllowed",
            "refusalReasons",
            "candidateChanges",
            "productionPromotionClaimed",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "proposalId": {"type": "string", "minLength": 1},
            "taskShape": {"type": ["string", "null"]},
            "sourceRecommendationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "regressionSignals": {"type": "object"},
            "advisoryOnly": {"const": True},
            "autoApply": {"const": False},
            "applyAllowed": {"type": "boolean"},
            "refusalReasons": {"type": "array", "items": {"type": "object"}},
            "candidateChanges": {"type": "array", "items": {"type": "object"}},
            "expectedBenefit": {"type": "object"},
            "qualityConstraints": {"type": "object"},
            "rollback": {"type": "object"},
            "compactSummary": {"type": "object"},
            "productionPromotionClaimed": {"const": False},
            "proposalDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-lifecycle-policy-summary.v1": open_object_schema(
        "agent-lifecycle-policy-summary.v1",
        required=[
            "schemaVersion",
            "latestUserIntent",
            "activeDecisions",
            "openBlockers",
            "acceptedEvidence",
            "changedFiles",
            "nextRequiredAction",
            "doNotDo",
            "applyAllowed",
            "candidateChanges",
            "qualityConstraints",
        ],
        properties={
            "activeDecisions": {"type": "array", "items": {"type": "string"}},
            "openBlockers": {"type": "array"},
            "acceptedEvidence": {"type": "array", "items": {"type": "object"}},
            "changedFiles": {"type": "array", "items": {"type": "string"}},
            "nextRequiredAction": {"type": "string"},
            "doNotDo": {"type": "array", "items": {"type": "string"}},
            "applyAllowed": {"type": "boolean"},
            "candidateChanges": {"type": "array", "items": {"type": "object"}},
            "qualityConstraints": {"type": "object"},
        },
    ),
    "agent-lifecycle-tuned-policy.v1": open_object_schema(
        "agent-lifecycle-tuned-policy.v1",
        required=[
            "schemaVersion",
            "status",
            "sourceProposalDigest",
            "changes",
            "rollback",
            "qualityConstraints",
            "productionPromotionClaimed",
            "policyDigest",
        ],
        properties={
            "status": {"const": "PASS"},
            "sourceProposalDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "changes": {"type": "array", "items": {"type": "object"}},
            "rollback": {"type": "object"},
            "qualityConstraints": {"type": "object"},
            "productionPromotionClaimed": {"const": False},
            "policyDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-lifecycle-policy-apply-result.v1": open_object_schema(
        "agent-lifecycle-policy-apply-result.v1",
        required=[
            "schemaVersion",
            "status",
            "outputPath",
            "outputDigest",
            "proposalDigest",
            "changed",
            "liveCallsStarted",
            "productionPromotionClaimed",
        ],
        properties={
            "status": {"const": "PASS"},
            "outputPath": {"type": "string"},
            "outputBytes": {"type": "integer", "minimum": 0},
            "outputDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "proposalDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "changed": {"type": "boolean"},
            "liveCallsStarted": {"const": False},
            "productionPromotionClaimed": {"const": False},
            "applyDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-lifecycle-policy-tune-result.v1": open_object_schema(
        "agent-lifecycle-policy-tune-result.v1",
        required=[
            "schemaVersion",
            "status",
            "mode",
            "proposal",
            "proposalDigest",
            "liveCallsStarted",
            "productionPromotionClaimed",
        ],
        properties={
            "status": {"const": "PASS"},
            "mode": {"enum": ["dry-run", "apply"]},
            "proposal": {"type": "object"},
            "proposalDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "applyResult": {"type": ["object", "null"]},
            "applyDigest": {"type": ["string", "null"]},
            "liveCallsStarted": {"const": False},
            "productionPromotionClaimed": {"const": False},
            "resultDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
}
