"""Built-in JSON schema definitions for workflow progress hook contracts."""

from __future__ import annotations

from typing import Any

from agent_lifecycle.contracts.schema_builders import open_object_schema as _open_object_schema

PROGRESS_HOOK_SCHEMAS: dict[str, dict[str, Any]] = {
    "agent-progress-hook-policy.v1": _open_object_schema(
        "agent-progress-hook-policy.v1",
        required=[
            "schemaVersion",
            "status",
            "hookMode",
            "allowedHookModes",
            "allowedCommands",
            "allowedHookPoints",
            "envVar",
            "defaultEnabled",
            "stdoutJsonPreserved",
            "stderrOnly",
            "receiptPathAllowed",
            "readOnly",
            "modelCallsStarted",
            "stateWritten",
            "tokenSpendForProgress",
            "pluginInstalledIsLifecycleProof",
            "autoClaimRequiresManagedWorkflowProof",
            "productionPromotionClaimed",
            "policyDigest",
        ],
        properties={
            "status": {"const": "PASS"},
            "hookMode": {"enum": ["off", "stderr", "receipt"]},
            "allowedHookModes": {"type": "array", "items": {"enum": ["off", "stderr", "receipt"]}},
            "allowedCommands": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "allowedHookPoints": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "envVar": {"const": "ALK_PROGRESS_HOOK"},
            "defaultEnabled": {"const": False},
            "stdoutJsonPreserved": {"const": True},
            "stderrOnly": {"type": "boolean"},
            "receiptPathAllowed": {"type": "boolean"},
            "readOnly": {"const": True},
            "modelCallsStarted": {"const": False},
            "stateWritten": {"const": False},
            "tokenSpendForProgress": {"const": False},
            "pluginInstalledIsLifecycleProof": {"const": False},
            "autoClaimRequiresManagedWorkflowProof": {"const": True},
            "productionPromotionClaimed": {"const": False},
            "policyDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-progress-hook-receipt.v1": _open_object_schema(
        "agent-progress-hook-receipt.v1",
        required=[
            "schemaVersion",
            "status",
            "adapterId",
            "supportLevel",
            "command",
            "hookPoint",
            "hookMode",
            "displayMode",
            "managedWorkflow",
            "managedWorkflowProof",
            "autoClaimAllowed",
            "pluginInstalledIsLifecycleProof",
            "stdoutJsonPreserved",
            "readOnly",
            "modelCallsStarted",
            "stateWritten",
            "tokenSpendForProgress",
            "tokenCountsInferred",
            "hostTelemetryParsedInCore",
            "stateIdentity",
            "progressIdentity",
            "bridgeDigest",
            "terminalText",
            "renderedLines",
            "productionPromotionClaimed",
            "receiptDigest",
        ],
        properties={
            "status": {"enum": ["EMITTED", "RECORDED"]},
            "adapterId": {"type": "string", "minLength": 1},
            "supportLevel": {"enum": ["AUTO", "WATCH", "MANUAL", "UNSUPPORTED"]},
            "command": {"type": "string", "minLength": 1},
            "hookPoint": {
                "enum": [
                    "after-workflow-run",
                    "after-task-result",
                    "after-task-accept",
                    "after-finalize",
                ]
            },
            "hookMode": {"enum": ["stderr", "receipt"]},
            "displayMode": {"const": "terminal"},
            "managedWorkflow": {"type": "boolean"},
            "managedWorkflowProof": {"type": "object"},
            "autoClaimAllowed": {"type": "boolean"},
            "pluginInstalledIsLifecycleProof": {"const": False},
            "stdoutJsonPreserved": {"const": True},
            "readOnly": {"const": True},
            "modelCallsStarted": {"const": False},
            "stateWritten": {"const": False},
            "tokenSpendForProgress": {"const": False},
            "tokenCountsInferred": {"const": False},
            "hostTelemetryParsedInCore": {"const": False},
            "stateIdentity": {"type": "object"},
            "progressIdentity": {"type": "object"},
            "bridgeDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "terminalText": {"type": "string", "minLength": 1},
            "renderedLines": {"type": "array", "items": {"type": "string"}},
            "productionPromotionClaimed": {"const": False},
            "receiptDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
}
