"""Built-in JSON schemas for proof-integrity evidence contracts."""

from __future__ import annotations

from typing import Any

from agent_lifecycle.contracts.schema_builders import open_object_schema

PROOF_INTEGRITY_SCHEMAS: dict[str, dict[str, Any]] = {
    "agent-proof-finding.v1": open_object_schema(
        "agent-proof-finding.v1",
        required=[
            "schemaVersion",
            "findingId",
            "findingDigest",
            "identityFields",
            "sourceFindingDigest",
        ],
        properties={
            "findingId": {"type": "string", "minLength": 1},
            "findingDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "identityFields": {"type": "object"},
            "sourceFindingDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "severity": {"type": ["string", "null"]},
            "status": {"type": ["string", "null"]},
        },
    ),
    "agent-proof-finding-validation.v1": open_object_schema(
        "agent-proof-finding-validation.v1",
        required=["schemaVersion", "status", "blockers", "findingId", "validationDigest"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "findingId": {"type": ["string", "null"]},
            "validationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-root-cause-evidence.v1": open_object_schema(
        "agent-root-cause-evidence.v1",
        required=[
            "schemaVersion",
            "status",
            "findingId",
            "rootCause",
            "rootCauseDigest",
            "evidenceIds",
            "verifier",
            "productionPromotionClaimed",
            "evidenceDigest",
        ],
        properties={
            "status": {"enum": ["CONFIRMED", "REJECTED", "INCONCLUSIVE"]},
            "findingId": {"type": "string", "minLength": 1},
            "rootCause": {"type": "object"},
            "rootCauseDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "evidenceIds": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "verifier": {"type": "object"},
            "productionPromotionClaimed": {"const": False},
            "evidenceDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-root-cause-evidence-validation.v1": open_object_schema(
        "agent-root-cause-evidence-validation.v1",
        required=["schemaVersion", "status", "blockers", "rootCauseDigest", "validationDigest"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "rootCauseDigest": {"type": ["string", "null"], "minLength": 64, "maxLength": 64},
            "validationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-fix-impact-receipt.v1": open_object_schema(
        "agent-fix-impact-receipt.v1",
        required=[
            "schemaVersion",
            "status",
            "lineage",
            "changedFiles",
            "relatedFindingIds",
            "rootCauseDigests",
            "behaviorChanges",
            "preservedBehaviors",
            "validationEvidenceIds",
            "collateralDamage",
            "verifier",
            "productionPromotionClaimed",
            "impactDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL", "BLOCKED"]},
            "lineage": {"type": "object"},
            "changedFiles": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "relatedFindingIds": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "rootCauseDigests": {"type": "array", "items": {"type": "string", "minLength": 64, "maxLength": 64}},
            "behaviorChanges": {"type": "array", "items": {"type": "object"}},
            "preservedBehaviors": {"type": "array", "items": {"type": "object"}},
            "validationEvidenceIds": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "collateralDamage": {"type": "object"},
            "verifier": {"type": "object"},
            "productionPromotionClaimed": {"const": False},
            "impactDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-fix-impact-receipt-validation.v1": open_object_schema(
        "agent-fix-impact-receipt-validation.v1",
        required=["schemaVersion", "status", "blockers", "impactDigest", "validationDigest"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "impactDigest": {"type": ["string", "null"], "minLength": 64, "maxLength": 64},
            "validationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-receipt-hash-chain.v1": open_object_schema(
        "agent-receipt-hash-chain.v1",
        required=[
            "schemaVersion",
            "status",
            "chainId",
            "appendOnly",
            "entries",
            "blockers",
            "productionPromotionClaimed",
            "chainDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "chainId": {"type": "string", "minLength": 1},
            "appendOnly": {"const": True},
            "lineage": {"type": "object"},
            "entries": {"type": "array", "items": {"type": "object"}},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "productionPromotionClaimed": {"const": False},
            "chainDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-receipt-hash-chain-validation.v1": open_object_schema(
        "agent-receipt-hash-chain-validation.v1",
        required=["schemaVersion", "status", "blockers", "chainDigest", "chainStatus", "entryCount", "validationDigest"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "chainDigest": {"type": ["string", "null"], "minLength": 64, "maxLength": 64},
            "chainStatus": {"type": ["string", "null"]},
            "entryCount": {"type": "integer", "minimum": 0},
            "validationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-hash-chain-migration-policy.v1": open_object_schema(
        "agent-hash-chain-migration-policy.v1",
        required=[
            "schemaVersion",
            "status",
            "mode",
            "newRunsRequireChain",
            "legacyReceiptPolicy",
            "allowedLegacyExemptions",
            "backfillBehavior",
            "productionPromotionClaimed",
            "policyDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "mode": {"const": "required-for-new-runs"},
            "newRunsRequireChain": {"const": True},
            "legacyReceiptPolicy": {"const": "explicit-exemption-or-backfill"},
            "allowedLegacyExemptions": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "backfillBehavior": {"type": "string", "minLength": 1},
            "productionPromotionClaimed": {"const": False},
            "policyDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-hash-chain-migration-validation.v1": open_object_schema(
        "agent-hash-chain-migration-validation.v1",
        required=["schemaVersion", "status", "newRun", "blockers", "policyDigest", "validationDigest"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "newRun": {"type": "boolean"},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "policyDigest": {"type": ["string", "null"], "minLength": 64, "maxLength": 64},
            "validationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-proof-integrity-receipt.v1": open_object_schema(
        "agent-proof-integrity-receipt.v1",
        required=[
            "schemaVersion",
            "status",
            "lineage",
            "findings",
            "rootCauses",
            "fixImpactReceipts",
            "hashChain",
            "migrationPolicy",
            "blockers",
            "verifier",
            "productionPromotionClaimed",
            "receiptDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "lineage": {"type": "object"},
            "requiredEvidenceIds": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "findings": {"type": "array", "items": {"type": "object"}},
            "rootCauses": {"type": "array", "items": {"type": "object"}},
            "fixImpactReceipts": {"type": "array", "items": {"type": "object"}},
            "hashChain": {"type": "object"},
            "migrationPolicy": {"type": "object"},
            "legacyHashChainExemption": {"type": "object"},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "verifier": {"type": "object"},
            "productionPromotionClaimed": {"const": False},
            "receiptDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-proof-integrity-validation.v1": open_object_schema(
        "agent-proof-integrity-validation.v1",
        required=[
            "schemaVersion",
            "status",
            "findingCount",
            "rootCauseCount",
            "fixImpactCount",
            "chainStatus",
            "blockers",
            "receiptDigest",
            "validationDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "findingCount": {"type": "integer", "minimum": 0},
            "rootCauseCount": {"type": "integer", "minimum": 0},
            "fixImpactCount": {"type": "integer", "minimum": 0},
            "chainStatus": {"type": ["string", "null"]},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "receiptDigest": {"type": ["string", "null"], "minLength": 64, "maxLength": 64},
            "validationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
}
