"""Built-in JSON schemas for optional Review Mesh contracts."""

from __future__ import annotations

from typing import Any

from agent_lifecycle.contracts.schema_builders import open_object_schema

REVIEW_MESH_MODE_IDS = (
    "leader-draft-multi-review",
    "parallel-research-synthesis",
    "implementation-audit-panel",
)

REVIEW_MESH_SCHEMAS: dict[str, dict[str, Any]] = {
    "agent-review-mesh-profile.v1": open_object_schema(
        "agent-review-mesh-profile.v1",
        required=[
            "schemaVersion",
            "profileId",
            "status",
            "enabledByDefault",
            "activationMode",
            "modes",
            "defaultMode",
            "advisoryByDefault",
            "blockingRequiresPlanOptIn",
            "requiresExplicitActivation",
            "budgetUnits",
            "budgetCap",
            "independencePolicy",
            "reviewerModelClasses",
            "crossCheckProfile",
            "concreteProviderModelNamesInPortableContract",
            "productionPromotionClaimed",
            "profileDigest",
        ],
        properties={
            "profileId": {"type": "string", "minLength": 1},
            "status": {"const": "OPTIONAL"},
            "enabledByDefault": {"const": False},
            "activationMode": {"const": "opt-in"},
            "modes": {"type": "array", "items": {"enum": list(REVIEW_MESH_MODE_IDS)}},
            "defaultMode": {"enum": list(REVIEW_MESH_MODE_IDS)},
            "advisoryByDefault": {"const": True},
            "blockingRequiresPlanOptIn": {"const": True},
            "requiresExplicitActivation": {"const": True},
            "liveCallsAllowed": {"type": "boolean"},
            "budgetUnits": {"const": "tokens-and-resources"},
            "budgetCap": {"type": "object"},
            "independencePolicy": {"type": "object"},
            "reviewerModelClasses": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "crossCheckProfile": {"type": "object"},
            "concreteProviderModelNamesInPortableContract": {"const": False},
            "productionPromotionClaimed": {"const": False},
            "profileDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-review-mesh-assignment.v1": open_object_schema(
        "agent-review-mesh-assignment.v1",
        required=[
            "schemaVersion",
            "assignmentId",
            "profileId",
            "profileDigest",
            "mode",
            "phase",
            "subject",
            "reviewer",
            "budgetCap",
            "blocking",
            "advisory",
            "productionPromotionClaimed",
            "assignmentDigest",
        ],
        properties={
            "assignmentId": {"type": "string", "minLength": 1},
            "profileId": {"type": "string", "minLength": 1},
            "profileDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "mode": {"enum": list(REVIEW_MESH_MODE_IDS)},
            "phase": {"type": "string", "minLength": 1},
            "subject": {"type": "object"},
            "reviewer": {"type": "object"},
            "budgetCap": {"type": "object"},
            "blocking": {"type": "boolean"},
            "advisory": {"type": "boolean"},
            "evidenceIds": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "independenceRequirement": {"type": ["object", "null"]},
            "productionPromotionClaimed": {"const": False},
            "assignmentDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-review-mesh-result.v1": open_object_schema(
        "agent-review-mesh-result.v1",
        required=[
            "schemaVersion",
            "status",
            "resultId",
            "assignmentId",
            "profileId",
            "profileDigest",
            "mode",
            "phase",
            "subject",
            "reviewer",
            "findings",
            "budgetUsage",
            "independence",
            "crossCheckReceipt",
            "blockers",
            "productionPromotionClaimed",
            "resultDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL", "SKIPPED"]},
            "resultId": {"type": "string", "minLength": 1},
            "assignmentId": {"type": "string", "minLength": 1},
            "profileId": {"type": "string", "minLength": 1},
            "profileDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "mode": {"enum": list(REVIEW_MESH_MODE_IDS)},
            "phase": {"type": "string", "minLength": 1},
            "subject": {"type": "object"},
            "reviewer": {"type": "object"},
            "independenceRequirement": {"type": ["object", "null"]},
            "findings": {"type": "array", "items": {"type": "object"}},
            "budgetUsage": {"type": "object"},
            "independence": {"type": "object"},
            "crossCheckReceipt": {"type": "object"},
            "independentEvidence": {"type": ["object", "null"]},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "productionPromotionClaimed": {"const": False},
            "resultDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-review-mesh-synthesis.v1": open_object_schema(
        "agent-review-mesh-synthesis.v1",
        required=[
            "schemaVersion",
            "status",
            "profileId",
            "profileDigest",
            "mode",
            "subject",
            "resultDigests",
            "agreement",
            "conflicts",
            "acceptedFindings",
            "rejectedFindings",
            "unresolvedFindings",
            "productionPromotionClaimed",
            "synthesisDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL", "INCONCLUSIVE"]},
            "profileId": {"type": "string", "minLength": 1},
            "profileDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "mode": {"enum": list(REVIEW_MESH_MODE_IDS)},
            "subject": {"type": "object"},
            "resultDigests": {"type": "array", "items": {"type": "string", "minLength": 64, "maxLength": 64}},
            "agreement": {"type": "array", "items": {"type": "object"}},
            "conflicts": {"type": "array", "items": {"type": "object"}},
            "acceptedFindings": {"type": "array", "items": {"type": "object"}},
            "rejectedFindings": {"type": "array", "items": {"type": "object"}},
            "unresolvedFindings": {"type": "array", "items": {"type": "object"}},
            "productionPromotionClaimed": {"const": False},
            "synthesisDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-review-mesh-quorum-receipt.v1": open_object_schema(
        "agent-review-mesh-quorum-receipt.v1",
        required=[
            "schemaVersion",
            "status",
            "profileId",
            "profileDigest",
            "mode",
            "subject",
            "quorumPolicy",
            "reviewerCount",
            "requiredRolesSatisfied",
            "quorumSatisfied",
            "blockingFindingsUnresolved",
            "blockers",
            "productionPromotionClaimed",
            "receiptDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL", "SKIPPED"]},
            "profileId": {"type": "string", "minLength": 1},
            "profileDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "mode": {"enum": list(REVIEW_MESH_MODE_IDS)},
            "subject": {"type": "object"},
            "quorumPolicy": {"type": "object"},
            "reviewerCount": {"type": "integer", "minimum": 0},
            "requiredRolesSatisfied": {"type": "boolean"},
            "quorumSatisfied": {"type": "boolean"},
            "blockingFindingsUnresolved": {"type": "boolean"},
            "independenceRequirement": {"type": ["object", "null"]},
            "independentEvidence": {"type": "array", "items": {"type": "object"}},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "productionPromotionClaimed": {"const": False},
            "receiptDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-review-mesh-quorum-validation.v1": open_object_schema(
        "agent-review-mesh-quorum-validation.v1",
        required=[
            "schemaVersion",
            "status",
            "profileId",
            "mode",
            "quorumSatisfied",
            "blockers",
            "receiptDigest",
            "validationDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "profileId": {"type": ["string", "null"]},
            "mode": {"type": ["string", "null"]},
            "quorumSatisfied": {"type": ["boolean", "null"]},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "receiptDigest": {"type": ["string", "null"], "minLength": 64, "maxLength": 64},
            "validationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
}
