"""Built-in JSON schemas for sandbox boundary receipts and policies."""

from __future__ import annotations

from typing import Any

from agent_lifecycle.contracts.schema_builders import open_object_schema

SANDBOX_SCHEMAS: dict[str, dict[str, Any]] = {
    "agent-sandbox-receipt.v1": open_object_schema(
        "agent-sandbox-receipt.v1",
        required=[
            "schemaVersion",
            "status",
            "lineage",
            "taskId",
            "attempt",
            "boundaries",
            "enforcement",
            "writeScopeBoundary",
            "verifier",
            "productionPromotionClaimed",
            "receiptDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL", "UNKNOWN", "UNSUPPORTED"]},
            "lineage": {"type": "object"},
            "taskId": {"type": "string", "minLength": 1},
            "attempt": {"type": "integer", "minimum": 1},
            "boundaries": {"type": "object"},
            "enforcement": {"type": "object"},
            "writeScopeBoundary": {"type": "object"},
            "evidenceIds": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "policyDigest": {"type": ["string", "null"], "minLength": 64, "maxLength": 64},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "verifier": {"type": "object"},
            "createdAt": {"type": "string", "minLength": 1},
            "productionPromotionClaimed": {"const": False},
            "receiptDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-sandbox-receipt-validation.v1": open_object_schema(
        "agent-sandbox-receipt-validation.v1",
        required=[
            "schemaVersion",
            "status",
            "sandboxStatus",
            "taskId",
            "attempt",
            "unknownBoundaryCount",
            "blockers",
            "receiptDigest",
            "validationDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "sandboxStatus": {"type": ["string", "null"]},
            "taskId": {"type": ["string", "null"]},
            "attempt": {"type": ["integer", "null"], "minimum": 1},
            "unknownBoundaryCount": {"type": "integer", "minimum": 0},
            "partialBoundaryCount": {"type": "integer", "minimum": 0},
            "credentialProxyCount": {"type": "integer", "minimum": 0},
            "credentialProxyRedacted": {"type": "boolean"},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "receiptDigest": {"type": ["string", "null"], "minLength": 64, "maxLength": 64},
            "validationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-sandbox-requirement.v1": open_object_schema(
        "agent-sandbox-requirement.v1",
        required=[
            "schemaVersion",
            "mode",
            "requireForHighRisk",
            "highRiskClasses",
            "acceptedSandboxStatuses",
            "failClosed",
            "productionPromotionClaimed",
            "policyDigest",
        ],
        properties={
            "mode": {"enum": ["off", "advisory", "required"]},
            "requireForHighRisk": {"type": "boolean"},
            "highRiskClasses": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "acceptedSandboxStatuses": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "failClosed": {"const": True},
            "productionPromotionClaimed": {"const": False},
            "policyDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-sandbox-requirement-validation.v1": open_object_schema(
        "agent-sandbox-requirement-validation.v1",
        required=[
            "schemaVersion",
            "status",
            "required",
            "taskId",
            "sandboxStatus",
            "blockers",
            "policyDigest",
            "receiptDigest",
            "validationDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "required": {"type": "boolean"},
            "taskId": {"type": ["string", "null"]},
            "sandboxStatus": {"type": ["string", "null"]},
            "acceptedSandboxStatuses": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "policyDigest": {"type": ["string", "null"], "minLength": 64, "maxLength": 64},
            "receiptDigest": {"type": ["string", "null"], "minLength": 64, "maxLength": 64},
            "validationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-sandbox-capability.v1": open_object_schema(
        "agent-sandbox-capability.v1",
        required=[
            "schemaVersion",
            "status",
            "boundaries",
            "enforcement",
            "writeScopeBoundary",
            "verified",
            "productionPromotionClaimed",
        ],
        properties={
            "status": {"enum": ["VERIFIED", "DECLARED", "UNKNOWN", "UNSUPPORTED"]},
            "boundaries": {"type": "object"},
            "enforcement": {"type": "object"},
            "writeScopeBoundary": {"type": "object"},
            "verified": {"type": "boolean"},
            "evidenceIds": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "notes": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "productionPromotionClaimed": {"const": False},
        },
    ),
    "agent-sandbox-capability-validation.v1": open_object_schema(
        "agent-sandbox-capability-validation.v1",
        required=[
            "schemaVersion",
            "status",
            "sandboxStatus",
            "unknownBoundaryCount",
            "blockers",
            "validationDigest",
        ],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "sandboxStatus": {"type": ["string", "null"]},
            "unknownBoundaryCount": {"type": "integer", "minimum": 0},
            "partialBoundaryCount": {"type": "integer", "minimum": 0},
            "credentialProxyCount": {"type": "integer", "minimum": 0},
            "credentialProxyRedacted": {"type": "boolean"},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "validationDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
}
