"""Built-in JSON schema registry for portable lifecycle envelopes."""

from __future__ import annotations

from copy import deepcopy
from typing import Any

SCHEMA_INDEX_VERSION = "agent-lifecycle-schema-index.v1"


def _open_object_schema(
    schema_id: str,
    *,
    required: list[str],
    properties: dict[str, Any] | None = None,
) -> dict[str, Any]:
    fields: dict[str, Any] = {"schemaVersion": {"const": schema_id}}
    fields.update(properties or {})
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": schema_id,
        "type": "object",
        "additionalProperties": True,
        "required": required,
        "properties": fields,
    }


_SCHEMAS: dict[str, dict[str, Any]] = {
    "agent-lifecycle-error.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "agent-lifecycle-error.v1",
        "type": "object",
        "additionalProperties": False,
        "required": ["schemaVersion", "code", "message", "details"],
        "properties": {
            "schemaVersion": {"const": "agent-lifecycle-error.v1"},
            "code": {"type": "string", "minLength": 1},
            "message": {"type": "string", "minLength": 1},
            "details": {"type": "object"},
        },
    },
    "agent-host-operation-request.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "agent-host-operation-request.v1",
        "type": "object",
        "additionalProperties": False,
        "required": [
            "schemaVersion",
            "operationId",
            "capability",
            "inputs",
            "outputs",
            "constraints",
        ],
        "properties": {
            "schemaVersion": {"const": "agent-host-operation-request.v1"},
            "operationId": {"type": "string", "minLength": 1},
            "capability": {"type": "string", "minLength": 1},
            "inputs": {"type": "object"},
            "outputs": {"type": "array", "items": {"type": "object"}},
            "constraints": {"type": "object"},
            "modelRoute": {"type": "object"},
        },
    },
    "agent-host-operation-receipt.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "agent-host-operation-receipt.v1",
        "type": "object",
        "additionalProperties": False,
        "required": [
            "schemaVersion",
            "operationId",
            "capability",
            "status",
            "outputs",
            "usage",
        ],
        "properties": {
            "schemaVersion": {"const": "agent-host-operation-receipt.v1"},
            "operationId": {"type": "string", "minLength": 1},
            "capability": {"type": "string", "minLength": 1},
            "status": {"enum": ["PASS", "FAIL", "BLOCKED"]},
            "outputs": {"type": "array", "items": {"type": "object"}},
            "usage": {"type": "object"},
        },
    },
    "agent-adapter-event.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "agent-adapter-event.v1",
        "type": "object",
        "additionalProperties": False,
        "required": [
            "schemaVersion",
            "eventId",
            "host",
            "adapterId",
            "runId",
            "taskId",
            "operationId",
            "sequence",
            "eventType",
            "status",
            "recordedAt",
            "payload",
        ],
        "properties": {
            "schemaVersion": {"const": "agent-adapter-event.v1"},
            "eventId": {"type": "string", "minLength": 1},
            "host": {"type": "string", "minLength": 1},
            "adapterId": {"type": "string", "minLength": 1},
            "runId": {"type": "string", "minLength": 1},
            "taskId": {"type": "string", "minLength": 1},
            "operationId": {"type": "string", "minLength": 1},
            "sequence": {"type": "integer", "minimum": 1},
            "eventType": {
                "enum": [
                    "session.started",
                    "task.launched",
                    "command.completed",
                    "writes.summarized",
                    "usage.reported",
                    "task.blocked",
                    "task.completed",
                ]
            },
            "status": {"enum": ["INFO", "PASS", "FAIL", "BLOCKED"]},
            "recordedAt": {"type": "string", "minLength": 1},
            "payload": {"type": "object"},
        },
    },
    "agent-adapter-event-stream-validation.v1": _open_object_schema(
        "agent-adapter-event-stream-validation.v1",
        required=["schemaVersion", "status", "eventCount", "eventTypes", "blockers"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "host": {"type": ["string", "null"]},
            "adapterId": {"type": ["string", "null"]},
            "runId": {"type": ["string", "null"]},
            "taskId": {"type": ["string", "null"]},
            "eventCount": {"type": "integer", "minimum": 0},
            "eventTypes": {"type": "array", "items": {"type": "string"}},
            "terminalEvent": {"type": ["string", "null"]},
            "blockers": {"type": "array", "items": {"type": "object"}},
        },
    ),
    "agent-completion-signal.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "agent-completion-signal.v1",
        "type": "object",
        "additionalProperties": True,
        "required": [
            "schemaVersion",
            "runId",
            "packageId",
            "planRevision",
            "planDigest",
            "sourceRevision",
            "status",
            "evidenceIds",
            "verifier",
        ],
        "properties": {
            "schemaVersion": {"const": "agent-completion-signal.v1"},
            "runId": {"type": "string", "minLength": 1},
            "packageId": {"type": "string", "minLength": 1},
            "planRevision": {"type": "integer", "minimum": 1},
            "planDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "sourceRevision": {"type": "string", "minLength": 1},
            "status": {"enum": ["PASS", "WAIVED", "FAIL"]},
            "evidenceIds": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "verifier": {"type": "object"},
            "waiver": {"type": "object"},
        },
    },
    "agent-completion-signal-validation.v1": _open_object_schema(
        "agent-completion-signal-validation.v1",
        required=["schemaVersion", "status", "signalStatus", "signalDigest", "waived"],
        properties={
            "status": {"const": "PASS"},
            "signalStatus": {"enum": ["PASS", "WAIVED"]},
            "signalDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "waived": {"type": "boolean"},
        },
    ),
    "agent-baseline-reconciliation-receipt.v1": _open_object_schema(
        "agent-baseline-reconciliation-receipt.v1",
        required=[
            "schemaVersion",
            "status",
            "taskId",
            "attempt",
            "expectedBaseRevision",
            "actualBaseRevision",
            "evidenceIds",
        ],
        properties={
            "status": {"const": "PASS"},
            "taskId": {"type": "string", "minLength": 1},
            "attempt": {"type": "integer", "minimum": 1},
            "expectedBaseRevision": {"type": "string", "minLength": 1},
            "actualBaseRevision": {"type": "string", "minLength": 1},
            "evidenceIds": {"type": "array", "items": {"type": "string", "minLength": 1}},
        },
    ),
    "agent-external-action-receipt.v1": _open_object_schema(
        "agent-external-action-receipt.v1",
        required=[
            "schemaVersion",
            "runId",
            "packageId",
            "planRevision",
            "planDigest",
            "sourceRevision",
            "actionId",
            "status",
            "evidenceIds",
        ],
        properties={
            "runId": {"type": "string", "minLength": 1},
            "packageId": {"type": "string", "minLength": 1},
            "planRevision": {"type": "integer", "minimum": 1},
            "planDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "sourceRevision": {"type": "string", "minLength": 1},
            "actionId": {"type": "string", "minLength": 1},
            "status": {"const": "PASS"},
            "evidenceIds": {"type": "array", "items": {"type": "string", "minLength": 1}},
        },
    ),
    "agent-host-adapter-validation.v1": _open_object_schema(
        "agent-host-adapter-validation.v1",
        required=["schemaVersion", "status", "adapterId", "host", "maturity", "blockers"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "adapterId": {"type": ["string", "null"]},
            "host": {"type": ["string", "null"]},
            "maturity": {"type": ["string", "null"]},
            "blockers": {"type": "array", "items": {"type": "object"}},
        },
    ),
    "agent-small-context-profile.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "agent-small-context-profile.v1",
        "type": "object",
        "additionalProperties": True,
        "required": ["schemaVersion", "profileId", "defaultWindow", "windows", "requiredSummaryFields"],
        "properties": {
            "schemaVersion": {"const": "agent-small-context-profile.v1"},
            "profileId": {"type": "string", "minLength": 1},
            "defaultWindow": {"enum": ["4k-strict", "8k", "16k", "32k", "64k"]},
            "windows": {"type": "object"},
            "requiredSummaryFields": {"type": "array", "items": {"type": "string"}},
        },
    },
    "agent-context-render-receipt.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "agent-context-render-receipt.v1",
        "type": "object",
        "additionalProperties": True,
        "required": ["schemaVersion", "status", "profileId", "window", "estimatedTokens", "checks", "envelopeDigest"],
        "properties": {
            "schemaVersion": {"const": "agent-context-render-receipt.v1"},
            "status": {"enum": ["PASS", "FAIL"]},
            "profileId": {"type": "string", "minLength": 1},
            "window": {"enum": ["4k-strict", "8k", "16k", "32k", "64k"]},
            "estimatedTokens": {"type": "object"},
            "checks": {"type": "array", "items": {"type": "object"}},
            "envelopeDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    },
    "agent-sdd-tier-resolution.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "agent-sdd-tier-resolution.v1",
        "type": "object",
        "additionalProperties": False,
        "required": ["schemaVersion", "tier", "reasons", "requestDigest", "rules"],
        "properties": {
            "schemaVersion": {"const": "agent-sdd-tier-resolution.v1"},
            "tier": {"enum": ["S0", "S1", "S2"]},
            "reasons": {"type": "array", "items": {"type": "string"}},
            "requestDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "rules": {"type": "object"},
        },
    },
    "agent-lifecycle-model-routing-profile.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "agent-lifecycle-model-routing-profile.v1",
        "type": "object",
        "additionalProperties": True,
        "required": ["schemaVersion", "profileId", "classes", "phaseRules"],
        "properties": {
            "schemaVersion": {"const": "agent-lifecycle-model-routing-profile.v1"},
            "profileId": {"type": "string", "minLength": 1},
            "classes": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "phaseRules": {"type": "object"},
        },
    },
    "agent-lifecycle-host-model-profile.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "agent-lifecycle-host-model-profile.v1",
        "type": "object",
        "additionalProperties": True,
        "required": ["schemaVersion", "host", "profileId", "bindings"],
        "properties": {
            "schemaVersion": {"const": "agent-lifecycle-host-model-profile.v1"},
            "host": {"type": "string", "minLength": 1},
            "profileId": {"type": "string", "minLength": 1},
            "bindings": {"type": "object"},
        },
    },
    "agent-host-model-selection-profile.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "agent-host-model-selection-profile.v1",
        "type": "object",
        "additionalProperties": True,
        "required": [
            "schemaVersion",
            "host",
            "profileId",
            "budgetModeDefault",
            "bindings",
            "fallbackPolicies",
            "redactionPolicy",
        ],
        "properties": {
            "schemaVersion": {"const": "agent-host-model-selection-profile.v1"},
            "host": {"type": "string", "minLength": 1},
            "profileId": {"type": "string", "minLength": 1},
            "budgetModeDefault": {"enum": ["metered", "subscription", "local"]},
            "bindings": {"type": "object"},
            "fallbackPolicies": {"type": "object"},
            "redactionPolicy": {"type": "object"},
        },
    },
    "agent-host-model-selection-receipt.v1": _open_object_schema(
        "agent-host-model-selection-receipt.v1",
        required=[
            "schemaVersion",
            "host",
            "routeDecisionDigest",
            "modelClass",
            "profileDigest",
            "bindingId",
            "bindingDigest",
            "providerModelHash",
            "fallbackUsed",
        ],
        properties={
            "host": {"type": "string", "minLength": 1},
            "routeDecisionDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "modelClass": {"type": "string", "minLength": 1},
            "profileDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "bindingId": {"type": "string", "minLength": 1},
            "bindingDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "providerModelHash": {"type": "string", "minLength": 64, "maxLength": 64},
            "fallbackUsed": {"type": "boolean"},
            "fallbackReason": {"type": ["string", "null"]},
        },
    ),
    "agent-lifecycle-budget-exceeded-policy.v1": _open_object_schema(
        "agent-lifecycle-budget-exceeded-policy.v1",
        required=[
            "schemaVersion",
            "mode",
            "allowedActions",
            "forbidDowngradeForCriticalReview",
            "maxAutoReroutesPerTask",
            "budgetModes",
        ],
        properties={
            "mode": {"enum": ["manual", "auto"]},
            "allowedActions": {
                "type": "array",
                "items": {
                    "enum": [
                        "continue-same-route",
                        "reroute-cheaper",
                        "reroute-stronger",
                        "split-task",
                        "abort",
                    ]
                },
            },
            "forbidDowngradeForCriticalReview": {"type": "boolean"},
            "maxAutoReroutesPerTask": {"type": "integer", "minimum": 0},
            "defaultAutoAction": {"type": "string"},
            "budgetModes": {"type": "object"},
        },
    ),
    "agent-lifecycle-budget-decision-receipt.v1": _open_object_schema(
        "agent-lifecycle-budget-decision-receipt.v1",
        required=[
            "schemaVersion",
            "runId",
            "taskId",
            "attemptId",
            "sourceRevision",
            "priorRouteDecisionDigest",
            "usageReceiptDigest",
            "overrunReason",
            "decisionMode",
            "selectedAction",
            "resumePhase",
            "expectedWorkflowRevision",
        ],
        properties={
            "runId": {"type": "string", "minLength": 1},
            "taskId": {"type": "string", "minLength": 1},
            "attemptId": {"type": "string", "minLength": 1},
            "sourceRevision": {"type": "string", "minLength": 1},
            "priorRouteDecisionDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "usageReceiptDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "overrunReason": {"type": "string", "minLength": 1},
            "decisionMode": {"enum": ["manual", "auto"]},
            "selectedAction": {"type": "string", "minLength": 1},
            "operatorIdentityHash": {"type": "string"},
            "policyDigest": {"type": "string"},
            "nextRouteDecisionDigest": {"type": ["string", "null"]},
            "capDeltas": {"type": "object"},
            "resumePhase": {"type": "string", "minLength": 1},
            "expectedWorkflowRevision": {"type": "integer", "minimum": 0},
        },
    ),
    "agent-cursor-compat-evidence.v1": _open_object_schema(
        "agent-cursor-compat-evidence.v1",
        required=["schemaVersion", "status", "source", "checks", "productionPromotionClaimed"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "source": {"type": "object"},
            "checks": {"type": "array", "items": {"type": "object"}},
            "providerModelHashes": {"type": "object"},
            "productionPromotionClaimed": {"const": False},
        },
    ),
    "agent-lifecycle-model-route-request.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "agent-lifecycle-model-route-request.v1",
        "type": "object",
        "additionalProperties": True,
        "required": ["schemaVersion", "operationId", "phase", "sddTier"],
        "properties": {
            "schemaVersion": {"const": "agent-lifecycle-model-route-request.v1"},
            "operationId": {"type": "string", "minLength": 1},
            "phase": {"type": "string", "minLength": 1},
            "sddTier": {"enum": ["S0", "S1", "S2"]},
        },
    },
    "agent-lifecycle-model-route-decision.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "agent-lifecycle-model-route-decision.v1",
        "type": "object",
        "additionalProperties": True,
        "required": ["schemaVersion", "operationId", "modelClass", "decisionDigest"],
        "properties": {
            "schemaVersion": {"const": "agent-lifecycle-model-route-decision.v1"},
            "operationId": {"type": "string", "minLength": 1},
            "modelClass": {"type": "string", "minLength": 1},
            "decisionDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    },
    "agent-lifecycle-model-usage-receipt.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "agent-lifecycle-model-usage-receipt.v1",
        "type": "object",
        "additionalProperties": True,
        "required": ["schemaVersion", "operationId", "host", "modelClass", "providerModelHash", "usage", "attestation"],
        "properties": {
            "schemaVersion": {"const": "agent-lifecycle-model-usage-receipt.v1"},
            "operationId": {"type": "string", "minLength": 1},
            "host": {"type": "string", "minLength": 1},
            "modelClass": {"type": "string", "minLength": 1},
            "providerModelHash": {"type": "string", "minLength": 1},
            "usage": {"type": "object"},
            "attestation": {"type": "object"},
        },
    },
    "agent-release-candidate-inventory.v1": _open_object_schema(
        "agent-release-candidate-inventory.v1",
        required=[
            "schemaVersion",
            "packageId",
            "planRevision",
            "planDigest",
            "files",
            "candidatePayloadInventoryDigest",
        ],
        properties={
            "packageId": {"type": "string", "minLength": 1},
            "planRevision": {"type": "integer", "minimum": 1},
            "planDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "files": {"type": "array", "items": {"type": "object"}},
            "candidatePayloadInventoryDigest": {"type": "string", "minLength": 64, "maxLength": 64},
        },
    ),
    "agent-release-assembly-evidence.v1": _open_object_schema(
        "agent-release-assembly-evidence.v1",
        required=["schemaVersion", "status", "inventory", "productionPromotionClaimed"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "inventory": {"type": "object"},
            "productionPromotionClaimed": {"const": False},
        },
    ),
    "agent-release-verification-evidence.v1": _open_object_schema(
        "agent-release-verification-evidence.v1",
        required=["schemaVersion", "status", "inventory", "mismatches", "productionPromotionClaimed"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "inventory": {"type": "object"},
            "mismatches": {"type": "array", "items": {"type": "object"}},
            "productionPromotionClaimed": {"const": False},
        },
    ),
    "agent-final-candidate-audit.v1": _open_object_schema(
        "agent-final-candidate-audit.v1",
        required=["schemaVersion", "status", "planRevision", "planDigest", "productionPromotionClaimed"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "semanticStatus": {"type": "string", "minLength": 1},
            "planRevision": {"type": "integer", "minimum": 1},
            "planDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "productionPromotionClaimed": {"const": False},
        },
    ),
    "agent-support-matrix-contract-evidence.v1": _open_object_schema(
        "agent-support-matrix-contract-evidence.v1",
        required=["schemaVersion", "status", "adapterMaturity", "productionPromotionClaimed"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "adapterMaturity": {"type": "string", "minLength": 1},
            "productionPromotionClaimed": {"const": False},
        },
    ),
    "agent-deferred-promotion-contract-evidence.v1": _open_object_schema(
        "agent-deferred-promotion-contract-evidence.v1",
        required=["schemaVersion", "status", "deferredProductionPromotion", "productionPromotionClaimed"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "deferredProductionPromotion": {"const": True},
            "productionPromotionClaimed": {"const": False},
        },
    ),
    "agent-neutrality-report.v1": _open_object_schema(
        "agent-neutrality-report.v1",
        required=["schemaVersion", "counters"],
        properties={
            "counters": {"type": "object"},
            "operation": {"type": "object"},
        },
    ),
    "agent-live-calibration-verification.v1": _open_object_schema(
        "agent-live-calibration-verification.v1",
        required=["schemaVersion", "status", "blockers", "productionPromotionClaimed"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "productionPromotionClaimed": {"const": False},
        },
    ),
    "agent-lifecycle-live-calibration-receipt.v1": _open_object_schema(
        "agent-lifecycle-live-calibration-receipt.v1",
        required=["schemaVersion", "status", "host", "runs", "syntheticReplayUsed"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "host": {"type": "string", "minLength": 1},
            "runs": {"type": "array", "items": {"type": "object"}},
            "syntheticReplayUsed": {"const": False},
        },
    ),
    "agent-lifecycle-live-host-conformance-receipt.v1": _open_object_schema(
        "agent-lifecycle-live-host-conformance-receipt.v1",
        required=["schemaVersion", "status", "host", "operations", "syntheticReplayUsed", "usageAttested"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "host": {"type": "string", "minLength": 1},
            "operations": {"type": "array", "items": {"type": "object"}},
            "syntheticReplayUsed": {"const": False},
            "usageAttested": {"const": True},
        },
    ),
    "agent-live-host-conformance-verification.v1": _open_object_schema(
        "agent-live-host-conformance-verification.v1",
        required=["schemaVersion", "status", "promotedHosts", "checks", "blockers", "productionPromotionClaimed"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "promotedHosts": {"type": "array", "items": {"type": "string"}},
            "checks": {"type": "array", "items": {"type": "object"}},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "productionPromotionClaimed": {"const": False},
        },
    ),
    "agent-live-host-promotion-plan.v1": _open_object_schema(
        "agent-live-host-promotion-plan.v1",
        required=[
            "schemaVersion",
            "packageId",
            "sddTier",
            "status",
            "intent",
            "hostOrder",
            "sequencingPolicy",
            "hostAvailabilitySnapshot",
            "sharedInputs",
            "artifactRootPolicy",
            "budgetPolicy",
            "blockerCodes",
            "operationEvidenceRequirements",
            "validationCommands",
            "evidenceArtifacts",
            "workstreams",
            "acceptanceCriteria",
        ],
        properties={
            "packageId": {"type": "string", "minLength": 1},
            "sddTier": {"enum": ["S0", "S1", "S2"]},
            "status": {"enum": ["DRAFT", "READY", "FROZEN", "BLOCKED"]},
            "intent": {"type": "string", "minLength": 1},
            "hostOrder": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "sequencingPolicy": {"type": "object"},
            "hostAvailabilitySnapshot": {"type": "object"},
            "sharedInputs": {"type": "object"},
            "artifactRootPolicy": {"type": "object"},
            "budgetPolicy": {"type": "object"},
            "blockerCodes": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "operationEvidenceRequirements": {"type": "object"},
            "validationCommands": {"type": "array", "items": {"type": "object"}},
            "evidenceArtifacts": {"type": "array", "items": {"type": "object"}},
            "workstreams": {"type": "array", "items": {"type": "object"}},
            "acceptanceCriteria": {"type": "array", "items": {"type": "object"}},
        },
    ),
    "agent-live-host-promotion-plan-validation.v1": _open_object_schema(
        "agent-live-host-promotion-plan-validation.v1",
        required=["schemaVersion", "status", "plan", "checks", "blockers", "productionPromotionClaimed"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "plan": {"type": "object"},
            "checks": {"type": "array", "items": {"type": "object"}},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "productionPromotionClaimed": {"const": False},
        },
    ),
    "agent-digest-authority-evidence.v1": _open_object_schema(
        "agent-digest-authority-evidence.v1",
        required=["schemaVersion", "status", "canonicalAuthority", "checks", "productionPromotionClaimed"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "canonicalAuthority": {"type": "string", "minLength": 1},
            "checks": {"type": "array", "items": {"type": "object"}},
            "productionPromotionClaimed": {"const": False},
        },
    ),
    "agent-docs-compat-evidence.v1": _open_object_schema(
        "agent-docs-compat-evidence.v1",
        required=["schemaVersion", "status", "checks", "blockers", "productionPromotionClaimed"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "checks": {"type": "array", "items": {"type": "object"}},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "productionPromotionClaimed": {"const": False},
        },
    ),
    "agent-negative-suite-coverage.v1": _open_object_schema(
        "agent-negative-suite-coverage.v1",
        required=["schemaVersion", "status", "expectedRange", "coveredScenarios"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "expectedRange": {"type": "string", "minLength": 1},
            "coveredScenarios": {"type": "array", "items": {"type": "object"}},
        },
    ),
    "agent-task-packet-context-fit.v1": _open_object_schema(
        "agent-task-packet-context-fit.v1",
        required=["schemaVersion", "status", "targetWindows", "checks"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "targetWindows": {"type": "array", "items": {"type": "string"}},
            "checks": {"type": "array", "items": {"type": "object"}},
        },
    ),
    "agent-packaging-smoke-evidence.v1": _open_object_schema(
        "agent-packaging-smoke-evidence.v1",
        required=["schemaVersion", "status", "commands", "blockers", "productionPromotionClaimed"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "commands": {"type": "array", "items": {"type": "object"}},
            "blockers": {"type": "array", "items": {"type": "object"}},
            "productionPromotionClaimed": {"const": False},
        },
    ),
    "agent-adapter-scaffold-result.v1": _open_object_schema(
        "agent-adapter-scaffold-result.v1",
        required=["schemaVersion", "status", "host", "maturity", "files", "productionPromotionClaimed"],
        properties={
            "status": {"enum": ["PASS", "DRY_RUN"]},
            "host": {"type": "string", "minLength": 1},
            "maturity": {"const": "EXPERIMENTAL"},
            "files": {"type": "array", "items": {"type": "object"}},
            "productionPromotionClaimed": {"const": False},
        },
    ),
    "agent-workflow-lineage-check.v1": _open_object_schema(
        "agent-workflow-lineage-check.v1",
        required=["schemaVersion", "status", "planRevision", "planDigest", "lineageChecks"],
        properties={
            "status": {"enum": ["PASS", "FAIL"]},
            "planRevision": {"type": "integer", "minimum": 1},
            "planDigest": {"type": "string", "minLength": 64, "maxLength": 64},
            "lineageChecks": {"type": "array", "items": {"type": "object"}},
        },
    ),
}


def list_schemas() -> dict[str, Any]:
    return {
        "schemaVersion": SCHEMA_INDEX_VERSION,
        "schemas": [
            {"id": schema_id, "draft": schema["$schema"]}
            for schema_id, schema in sorted(_SCHEMAS.items())
        ],
    }


def get_schema(schema_id: str) -> dict[str, Any]:
    if schema_id not in _SCHEMAS:
        from agent_lifecycle.contracts.errors import LifecycleError

        raise LifecycleError("unknown-schema", f"unknown schema: {schema_id}")
    return deepcopy(_SCHEMAS[schema_id])
