"""Argparse construction for lifecycle metrics commands."""

from __future__ import annotations

import argparse

from agent_lifecycle.resources import builtin_profile_path

_BASELINE_PROFILE = builtin_profile_path("lifecycle-baselines.v1.json")

MODES = ("light", "standard", "strict", "release")


def add_metrics_parser(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    metrics = subparsers.add_parser("metrics", help="resource and lifecycle metrics commands")
    metrics_sub = metrics.add_subparsers(dest="metrics_command", required=True)
    cost_check = metrics_sub.add_parser("cost-check")
    cost_check.add_argument("--receipt", required=True)
    cost_report = metrics_sub.add_parser("cost-report")
    cost_report.add_argument("--artifact", action="append", default=[])
    cost_report.add_argument("--mode", choices=MODES, default="standard")
    cost_report.add_argument("--project-root", default=".")
    cost_report.add_argument("--out", required=True)
    cost_report.add_argument("--summary-out")
    phase_resources = metrics_sub.add_parser("phase-resources", help="build a bounded phase resource measurement")
    phase_resources.add_argument("--input", required=True)
    phase_resources.add_argument("--out", required=True)
    release_accounting = metrics_sub.add_parser("release-accounting", help="build release resource accounting")
    release_accounting.add_argument("--release-id", required=True)
    release_accounting.add_argument("--artifact", action="append", required=True)
    release_accounting.add_argument("--project-root", default=".")
    release_accounting.add_argument("--provenance")
    release_accounting.add_argument("--out", required=True)
    usage_export = metrics_sub.add_parser("usage-export")
    usage_export.add_argument("--artifact", action="append", default=[])
    usage_export.add_argument("--project-root", default=".")
    usage_export.add_argument("--format", choices=("json", "table"), default="json")
    usage_export.add_argument("--out", required=True)
    execution_report = metrics_sub.add_parser("execution-report")
    execution_report.add_argument("--receipt", action="append", required=True)
    execution_report.add_argument("--operation-id")
    execution_report.add_argument("--out", required=True)
    outcome_index = metrics_sub.add_parser("outcome-index")
    outcome_index.add_argument("--artifact", action="append", default=[])
    outcome_index.add_argument("--out")
    quality_signals = metrics_sub.add_parser("quality-signals")
    quality_signals.add_argument("--index", required=True)
    quality_signals.add_argument("--out")
    recommend = metrics_sub.add_parser("recommend")
    recommend.add_argument("--report", action="append", default=[])
    recommend.add_argument("--baseline-profile", default=_BASELINE_PROFILE)
    recommend.add_argument("--task-shape", default="feature")
    recommend.add_argument("--current-mode", choices=MODES)
    recommend.add_argument("--sdd-tier")
    recommend.add_argument("--risk", action="append", default=[])
    recommend.add_argument("--out")
    recommend.add_argument("--summary-out")
    learn_recommend = metrics_sub.add_parser("learn-recommend")
    learn_recommend.add_argument("--signals", required=True)
    learn_recommend.add_argument("--baseline-profile", default=_BASELINE_PROFILE)
    learn_recommend.add_argument("--task-shape", default="feature")
    learn_recommend.add_argument("--current-mode", choices=MODES)
    learn_recommend.add_argument("--sdd-tier")
    learn_recommend.add_argument("--risk", action="append", default=[])
    learn_recommend.add_argument("--out")
    learn_recommend.add_argument("--summary-out")
    audit_sample = metrics_sub.add_parser("audit-sample", help="build a privacy-preserving audit sample batch")
    audit_sample.add_argument("--receipt", action="append", required=True)
    audit_sample.add_argument("--out", required=True)
    audit_report = metrics_sub.add_parser("audit-report", help="summarize audit quality, time, tokens and resources")
    audit_report.add_argument("--sample", action="append", required=True)
    audit_report.add_argument("--candidate-profile", action="append", default=[])
    audit_report.add_argument("--reference-task", action="append", default=[])
    audit_report.add_argument("--holdout-task", action="append", default=[])
    audit_report.add_argument("--task-shape", default="feature")
    audit_report.add_argument("--quality-floor", default="standard")
    audit_report.add_argument("--current-profile")
    audit_report.add_argument("--out", required=True)
    audit_report.add_argument("--terminal", action="store_true")
    audit_efficiency = metrics_sub.add_parser(
        "audit-efficiency",
        help="report quality-preserving audit efficiency from explicit accounting inputs",
    )
    audit_efficiency.add_argument("--input", required=True)
    audit_efficiency.add_argument("--comparison", action="append", default=[])
    audit_efficiency.add_argument("--out", required=True)
    audit_proposal = metrics_sub.add_parser("audit-proposal", help="create an explicit audit optimization proposal")
    audit_proposal.add_argument("--report", required=True)
    audit_proposal.add_argument("--out", required=True)
    audit_proposal.add_argument("--approved", action="store_true")
    audit_proposal.add_argument(
        "--target-kind", choices=("project-profile", "plan-revision"), default="project-profile"
    )
    audit_proposal.add_argument("--target-revision")
    audit_proposal.add_argument("--frozen-plan", action="store_true")
    audit_apply = metrics_sub.add_parser("audit-apply", help="write an approved new optimization profile artifact")
    audit_apply.add_argument("--proposal", required=True)
    audit_apply.add_argument("--out", required=True)
