"""Argparse construction for the root CLI."""

from __future__ import annotations

import argparse
from pathlib import Path

from agent_lifecycle.cli.adapter import add_adapter_parser
from agent_lifecycle.cli.followup import add_followup_parser
from agent_lifecycle.cli.metrics_parser import add_metrics_parser
from agent_lifecycle.cli.policy import add_policy_parser
from agent_lifecycle.cli.research import add_research_parser
from agent_lifecycle.cli.lifecycle_parsers import _add_host_launch_parser, _add_project_parser, _add_start_parser, _add_workflow_parser
from agent_lifecycle.cli.observability_parsers import _add_report_parser
from agent_lifecycle.cli.planning_parsers import _add_plan_parser, _add_task_parser
from agent_lifecycle.cli.worktree import add_worktree_parser
from agent_lifecycle.contracts.review_mesh_schemas import REVIEW_MESH_MODE_IDS
from agent_lifecycle.review_mesh.operator_templates import (
    REVIEW_MESH_OPERATOR_TEMPLATE_IDS,
)


def build_parser() -> argparse.ArgumentParser:
    parser = _RootArgumentParser(prog="agent-lifecycle")
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("version", help="print package version as compact JSON")
    _add_start_parser(subparsers)
    _add_host_launch_parser(subparsers)
    _add_diagnose_parser(subparsers)
    _add_diagnostics_parser(subparsers)
    _add_schema_parser(subparsers)
    _add_contract_parser(subparsers)
    subparsers.add_parser("neutrality", help="run neutrality subcommands")
    _add_evidence_parser(subparsers)
    add_research_parser(subparsers)
    _add_import_parser(subparsers)
    _add_quality_parser(subparsers)
    _add_review_mesh_parser(subparsers)
    _add_benchmark_parser(subparsers)
    _add_strategy_parser(subparsers)
    _add_report_parser(subparsers)
    add_policy_parser(subparsers)
    _add_workflow_parser(subparsers)
    _add_audit_parser(subparsers)
    _add_context_parser(subparsers)
    _add_thread_parser(subparsers)
    _add_goal_parser(subparsers)
    add_followup_parser(subparsers)
    add_worktree_parser(subparsers)
    _add_model_parser(subparsers)
    add_metrics_parser(subparsers)
    _add_runner_parser(subparsers)
    _add_tier_parser(subparsers)
    _add_specification_parser(subparsers)
    _add_plan_parser(subparsers)
    _add_task_parser(subparsers)
    add_adapter_parser(subparsers)
    _add_project_parser(subparsers)
    subparsers.add_parser("conformance", help="conformance commands")
    return parser


class _RootArgumentParser(argparse.ArgumentParser):
    """Keep the legacy adapter requirement unless a profile can supply it."""

    def parse_known_args(self, args=None, namespace=None):  # type: ignore[no-untyped-def]
        parsed, remainder = super().parse_known_args(args, namespace)
        if getattr(parsed, "command", None) == "start" and not getattr(parsed, "adapter", None):
            if getattr(parsed, "no_project_profile", False):
                self.error("start requires --adapter when --no-project-profile is used")
            explicit = getattr(parsed, "project_profile", None)
            discovered = Path.cwd() / ".alk" / "project-profile.json"
            if not explicit and not discovered.is_file():
                self.error("start requires --adapter or a project profile")
        return parsed, remainder


def _add_benchmark_parser(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    benchmark = subparsers.add_parser("benchmark", help="deterministic reference-task evaluation and qualification")
    benchmark_sub = benchmark.add_subparsers(dest="benchmark_command", required=True)
    evaluate = benchmark_sub.add_parser("evaluate")
    evaluate.add_argument("--suite", required=True)
    evaluate.add_argument("--artifact", required=True)
    evaluate.add_argument("--out")
    compare = benchmark_sub.add_parser("compare")
    compare.add_argument("--baseline", required=True)
    compare.add_argument("--candidate", required=True)
    compare.add_argument("--out")
    sample = benchmark_sub.add_parser("sample", aliases=["select"])
    sample.add_argument("--suite", required=True)
    sample.add_argument("--seed", default="default")
    sample.add_argument("--max-tasks", type=int, default=24)
    sample.add_argument("--max-strata", type=int, default=16)
    sample.add_argument("--out")
    receipt_check = benchmark_sub.add_parser("receipt-check", aliases=["validate-receipt"])
    receipt_check.add_argument("--suite")
    receipt_check.add_argument("--receipt", required=True)
    receipt_check.add_argument("--out")
    qualify = benchmark_sub.add_parser("qualify", aliases=["qualification"])
    qualify.add_argument("--suite")
    qualify.add_argument("--receipt", action="append", required=True)
    qualify.add_argument("--sample")
    qualify.add_argument("--out")
    route_compare = benchmark_sub.add_parser("compare-routes")
    route_compare.add_argument("--suite")
    route_compare.add_argument("--baseline", action="append", required=True)
    route_compare.add_argument("--candidate", action="append", required=True)
    route_compare.add_argument("--sample")
    route_compare.add_argument("--out")


def _add_strategy_parser(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    strategy = subparsers.add_parser("strategy", help="resolve provider-neutral execution strategy")
    strategy_sub = strategy.add_subparsers(dest="strategy_command", required=True)
    resolve = strategy_sub.add_parser("resolve")
    resolve.add_argument("--manifest", required=True)
    resolve.add_argument("--lock", required=True)
    resolve.add_argument("--state", required=True)
    resolve.add_argument("--task", required=True)
    resolve.add_argument("--operation-id", required=True)
    resolve.add_argument("--expected-revision", required=True, type=int)
    resolve.add_argument("--source-revision", required=True)
    resolve.add_argument("--adapter", required=True)
    resolve.add_argument("--descriptor")
    resolve.add_argument("--risk", choices=["auto", "S0", "S1", "S2"], default="auto")
    resolve.add_argument("--risk-policy", default="profiles/risk-execution-policy.v1.json")
    resolve.add_argument("--routing-profile", default="profiles/model-routing-profile.v1.json")
    resolve.add_argument("--baseline-profile", default="profiles/lifecycle-baselines.v1.json")
    resolve.add_argument("--host-model-profile")
    resolve.add_argument("--out", required=True)


def _add_diagnose_parser(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    diagnose = subparsers.add_parser("diagnose", help="build a redacted readiness report")
    diagnose.add_argument("--project-root", default=".")
    diagnose.add_argument("--adapter", action="append", default=[])
    diagnose.add_argument("--context-profile")
    diagnose.add_argument("--model-profile")
    diagnose.add_argument("--adapter-baseline")
    diagnose.add_argument("--no-install-plans", action="store_true")
    diagnose.add_argument("--include-host-probes", action="store_true")
    diagnose.add_argument("--timeout-seconds", type=float, default=5.0)
    diagnose.add_argument("--max-host-probes", type=int, default=1)


def _add_diagnostics_parser(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    diagnostics = subparsers.add_parser("diagnostics", help="optional diagnostics commands")
    diagnostics_sub = diagnostics.add_subparsers(dest="diagnostics_command", required=True)
    bundle = diagnostics_sub.add_parser("bundle")
    bundle.add_argument("--project-root", default=".")
    bundle.add_argument("--artifact", action="append", default=[])
    bundle.add_argument("--max-artifacts", type=int, default=8)
    bundle.add_argument("--max-input-bytes", type=int, default=20000)
    bundle.add_argument("--out")


def _add_schema_parser(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    schema = subparsers.add_parser("schema", help="inspect bundled JSON schemas")
    schema_sub = schema.add_subparsers(dest="schema_command", required=True)
    schema_sub.add_parser("list")
    show = schema_sub.add_parser("show")
    show.add_argument("schema_id")


def _add_contract_parser(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    contract = subparsers.add_parser("contract", help="public contract commands")
    contract_sub = contract.add_subparsers(dest="contract_command", required=True)
    policy = contract_sub.add_parser("policy")
    policy.add_argument("--out")
    check = contract_sub.add_parser("check")
    check.add_argument("--policy")


def _add_evidence_parser(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    evidence = subparsers.add_parser("evidence", help="optional evidence index commands")
    evidence_sub = evidence.add_subparsers(dest="evidence_command", required=True)
    index = evidence_sub.add_parser("index")
    index.add_argument("--project-root", default=".")
    index.add_argument("--artifact", action="append", default=[])
    index.add_argument("--max-artifacts", type=int, default=64)
    index.add_argument("--max-input-bytes", type=int, default=65536)
    index.add_argument("--target-tokens", type=int, default=2048)
    index.add_argument("--out")
    search = evidence_sub.add_parser("search")
    search.add_argument("--index", required=True)
    search.add_argument("--query", default="")
    search.add_argument("--max-results", type=int, default=8)
    search.add_argument("--target-tokens", type=int, default=2048)
    search.add_argument("--out")


def _add_import_parser(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    imports = subparsers.add_parser("import", help="optional import commands for untrusted planning inputs")
    import_sub = imports.add_subparsers(dest="import_command", required=True)
    profile_list = import_sub.add_parser("profile-list")
    profile_list.add_argument("--out")
    plan = import_sub.add_parser("plan")
    plan.add_argument("--source", required=True)
    plan.add_argument("--dialect", choices=["openspec", "spec-kit", "bmad", "spec-kitty"])
    plan.add_argument("--package-id", default="imported-plan")
    plan.add_argument("--max-input-bytes", type=int, default=32768)
    plan.add_argument("--max-files", type=int, default=32)
    plan.add_argument("--target-tokens", type=int, default=4096)
    plan.add_argument("--out")
    external = import_sub.add_parser("external")
    external.add_argument("--source", required=True)
    external.add_argument("--family", choices=["workflow", "agent"], required=True)
    external.add_argument("--profile", default="generic")
    external.add_argument("--package-id", default="external-dialect-import")
    external.add_argument("--max-input-bytes", type=int, default=32768)
    external.add_argument("--target-tokens", type=int, default=4096)
    external.add_argument("--out")
    check = import_sub.add_parser("check")
    check.add_argument("--candidate", required=True)
    external_check = import_sub.add_parser("external-check")
    external_check.add_argument("--candidate", required=True)
    proposal_check = import_sub.add_parser("proposal-check")
    proposal_check.add_argument("--proposal", required=True)


def _add_quality_parser(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    quality = subparsers.add_parser("quality", help="optional quality commands")
    quality_sub = quality.add_subparsers(dest="quality_command", required=True)
    pack_check = quality_sub.add_parser("pack-check")
    pack_check.add_argument("--manifest")
    behavior_check = quality_sub.add_parser("behavior-check")
    behavior_check.add_argument("--manifest")
    behavior_check.add_argument("--fixture", action="append", default=[])
    template_list = quality_sub.add_parser("template-list")
    template_list.add_argument("--out")
    template_check = quality_sub.add_parser("template-check")
    template_check.add_argument("--project-root", default=".")
    template_check.add_argument("--template-id")
    template_check.add_argument("--out")
    bug_recipe_list = quality_sub.add_parser("bug-recipe-list")
    bug_recipe_list.add_argument("--out")
    bug_recipe_check = quality_sub.add_parser("bug-recipe-check")
    bug_recipe_check.add_argument("--recipe-id")
    bug_recipe_check.add_argument("--out")


def _add_review_mesh_parser(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    review_mesh = subparsers.add_parser("review-mesh", help="optional Review Mesh commands")
    review_mesh_sub = review_mesh.add_subparsers(dest="review_mesh_command", required=True)
    template_list = review_mesh_sub.add_parser("template-list")
    template_list.add_argument("--out")
    profile = review_mesh_sub.add_parser("profile")
    profile.add_argument("--profile-id", default="optional-review-mesh")
    profile.add_argument("--mode", choices=list(REVIEW_MESH_MODE_IDS), action="append", default=[])
    profile.add_argument("--default-mode", choices=list(REVIEW_MESH_MODE_IDS), default="leader-draft-multi-review")
    profile.add_argument("--reviewer-model-class", action="append", default=[])
    profile.add_argument("--require-independence", action="store_true")
    profile.add_argument("--independence-dimension", choices=["host", "model"], action="append", default=[])
    profile.add_argument("--allow-live-calls", action="store_true")
    profile.add_argument("--max-invocations", type=int)
    profile.add_argument("--max-input-tokens", type=int)
    profile.add_argument("--max-output-tokens", type=int)
    profile.add_argument("--max-wall-seconds", type=int)
    profile.add_argument("--out")
    recommend = review_mesh_sub.add_parser("recommend")
    source = recommend.add_mutually_exclusive_group(required=True)
    source.add_argument("--text")
    source.add_argument("--file")
    source.add_argument("--intake")
    source.add_argument("--manifest")
    recommend.add_argument("--sdd-tier", choices=["S0", "S1", "S2"])
    recommend.add_argument("--risk-flag", action="append", default=[])
    recommend.add_argument("--out")
    prepare = review_mesh_sub.add_parser("prepare")
    prepare_source = prepare.add_mutually_exclusive_group(required=True)
    prepare_source.add_argument("--manifest")
    prepare_source.add_argument("--intake")
    prepare_source.add_argument("--handoff")
    prepare.add_argument("--template", choices=list(REVIEW_MESH_OPERATOR_TEMPLATE_IDS), default="leader-draft-review")
    prepare.add_argument("--profile-id")
    prepare.add_argument("--phase")
    prepare.add_argument("--reviewer", action="append", default=[])
    prepare.add_argument("--blocking", action="store_true")
    prepare.add_argument("--evidence-id", action="append", default=[])
    prepare.add_argument("--out-dir")
    prepare.add_argument("--out")
    assign = review_mesh_sub.add_parser("assign")
    assign_source = assign.add_mutually_exclusive_group(required=True)
    assign_source.add_argument("--manifest")
    assign_source.add_argument("--intake")
    assign_source.add_argument("--handoff")
    assign.add_argument("--profile")
    assign.add_argument("--mode", choices=list(REVIEW_MESH_MODE_IDS), required=True)
    assign.add_argument("--phase", required=True)
    assign.add_argument("--assignment-id", required=True)
    assign.add_argument("--reviewer-id", required=True)
    assign.add_argument("--reviewer-role", default="reviewer")
    assign.add_argument("--reviewer-model-class", default="strong-reasoning")
    assign.add_argument("--reviewer-host-identity-hash")
    assign.add_argument("--reviewer-model-identity-hash")
    assign.add_argument("--blocking", action="store_true")
    assign.add_argument("--evidence-id", action="append", default=[])
    assign.add_argument("--out")
    import_result = review_mesh_sub.add_parser("import-result")
    import_result.add_argument("--profile", required=True)
    import_result.add_argument("--assignment", required=True)
    import_result.add_argument("--reviewer-output", required=True)
    import_result.add_argument("--allow-local-evidence-ref", action="store_true")
    import_result.add_argument("--out")
    synthesize = review_mesh_sub.add_parser("synthesize")
    synthesize.add_argument("--profile", required=True)
    synthesize.add_argument("--result", action="append", required=True)
    synthesize.add_argument("--mode", choices=list(REVIEW_MESH_MODE_IDS))
    synthesize.add_argument("--accepted-finding-id", action="append", default=[])
    synthesize.add_argument("--rejected-finding-id", action="append", default=[])
    synthesize.add_argument("--out")
    quorum = review_mesh_sub.add_parser("quorum")
    quorum.add_argument("--profile", required=True)
    quorum.add_argument("--synthesis", required=True)
    quorum.add_argument("--min-reviewers", type=int, required=True)
    quorum.add_argument("--required-role", action="append", default=[])
    quorum.add_argument("--reviewer-role", action="append", default=[])
    quorum.add_argument("--out")


def _add_audit_parser(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    audit = subparsers.add_parser("audit", help="audit commands")
    audit_sub = audit.add_subparsers(dest="audit_command", required=True)
    ownership = audit_sub.add_parser("ownership")
    ownership.add_argument("--manifest", required=True)
    ownership.add_argument("--base", required=False)
    ownership.add_argument("--path", action="append", default=[])
    ownership.add_argument("--fail-on-unowned", action="store_true")
    ownership.add_argument("--fail-on-forbidden", action="store_true")
    review_check = audit_sub.add_parser("review-check")
    review_check.add_argument("--review", required=True)
    implementation = audit_sub.add_parser("implementation")
    implementation.add_argument("--manifest", required=True)
    implementation.add_argument("--state", required=True)
    implementation.add_argument("--task", required=True)
    implementation.add_argument("--result", required=True)
    implementation.add_argument("--review", required=True)
    implementation.add_argument("--evidence", action="append", default=[])
    implementation.add_argument("--sandbox-receipt", action="append", default=[])
    implementation.add_argument("--review-mesh-quorum", action="append", default=[])
    implementation.add_argument("--path", action="append", default=[])
    implementation.add_argument("--base")
    implementation.add_argument("--expected-revision", type=int)
    implementation.add_argument("--auditor-id", default="implementation-auditor")
    implementation.add_argument("--auditor-surface", default="cli")
    implementation.add_argument("--out")
    final_implementation = audit_sub.add_parser("final-implementation")
    final_implementation.add_argument("--manifest", required=True)
    final_implementation.add_argument("--state", required=True)
    final_implementation.add_argument("--report", action="append", required=True)
    final_implementation.add_argument("--auditor-id", default="final-implementation-auditor")
    final_implementation.add_argument("--auditor-surface", default="cli")
    final_implementation.add_argument("--out")
    package = audit_sub.add_parser("package")
    package.add_argument("--plan-dir", required=True)
    package.add_argument("--state")
    package.add_argument("--report", action="append", default=[])
    package.add_argument("--path", action="append", default=[])
    package.add_argument("--base")
    package.add_argument("--completeness-profile")
    package.add_argument("--require-frozen", action="store_true")
    package.add_argument("--require-implementation", action="store_true")
    package.add_argument("--strict", action="store_true")
    package.add_argument("--auditor-id", default="package-auditor")
    package.add_argument("--auditor-surface", default="cli")
    package.add_argument("--out")


def _add_context_parser(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    context = subparsers.add_parser("context", help="compact context commands")
    context_sub = context.add_subparsers(dest="context_command", required=True)
    profile_check = context_sub.add_parser("profile-check")
    profile_check.add_argument("--profile", required=True)
    context_check = context_sub.add_parser("check")
    context_check.add_argument("--profile", required=True)
    context_check.add_argument("--task-packet", required=True)
    context_check.add_argument("--summary", required=True)
    context_check.add_argument("--target-window")
    context_check.add_argument("--latest-user", default="")
    context_render = context_sub.add_parser("render")
    context_render.add_argument("--profile", required=True)
    context_render.add_argument("--task-packet", required=True)
    context_render.add_argument("--summary", required=True)
    context_render.add_argument("--target-window")
    context_render.add_argument("--latest-user", default="")
    external_import = context_sub.add_parser("external-import")
    external_import.add_argument("--source", required=True)
    external_import.add_argument("--citation")
    external_import.add_argument("--source-id")
    external_import.add_argument("--max-input-bytes", type=int, default=32768)
    external_import.add_argument("--target-tokens", type=int, default=2048)
    external_import.add_argument("--out")
    episode_retrieve = context_sub.add_parser("episode-retrieve")
    episode_retrieve.add_argument("--project-root", default=".")
    episode_retrieve.add_argument("--artifact", action="append", required=True)
    episode_retrieve.add_argument("--external-context", action="append", default=[])
    episode_retrieve.add_argument("--query", default="")
    episode_retrieve.add_argument("--max-results", type=int, default=8)
    episode_retrieve.add_argument("--max-external-context-hints", type=int, default=4)
    episode_retrieve.add_argument("--target-tokens", type=int, default=2048)
    episode_retrieve.add_argument("--out")
    checkpoint = context_sub.add_parser("checkpoint", help="write a bounded context checkpoint")
    checkpoint.add_argument("--session", required=True)
    checkpoint.add_argument("--state", required=True)
    checkpoint.add_argument("--plan", required=True)
    checkpoint.add_argument("--input", required=True)
    checkpoint.add_argument("--reason", required=True)
    checkpoint.add_argument(
        "--capture-mode",
        choices=["NATIVE_HOOK", "MILESTONE", "AGENT_REQUESTED", "UNAVAILABLE"],
        default=None,
    )
    checkpoint.add_argument("--adapter")
    checkpoint.add_argument("--out")
    restore = context_sub.add_parser("restore", help="restore a bounded context continuation")
    restore.add_argument("--checkpoint", required=True)
    restore.add_argument("--state", required=True)
    restore.add_argument("--session")
    restore.add_argument("--target-tokens", type=int, default=2048)
    restore.add_argument("--out")


def _add_thread_parser(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    thread = subparsers.add_parser("thread", help="prepare optional host-thread bridge artifacts")
    thread_sub = thread.add_subparsers(dest="thread_command", required=True)
    request = thread_sub.add_parser("request", help="prepare a bounded thread operation request")
    request.add_argument("--operation", choices=["read", "list", "send", "create"], required=True)
    request.add_argument("--operation-id")
    request.add_argument("--scope", choices=["explicit-target", "project", "workflow"])
    request.add_argument("--target-hash")
    request.add_argument("--text")
    request.add_argument("--idempotency-key")
    request.add_argument("--phase")
    request.add_argument("--max-bytes", type=int, default=32768)
    request.add_argument("--max-tokens", type=int, default=2048)
    request.add_argument("--out", required=True)
    import_result = thread_sub.add_parser("import", help="validate a host receipt and import bounded context")
    import_result.add_argument("--request", required=True)
    import_result.add_argument("--receipt", required=True)
    import_result.add_argument("--source-id")
    import_result.add_argument("--citation")
    import_result.add_argument("--out", required=True)


def _add_goal_parser(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    goal = subparsers.add_parser("goal", help="goal continuity commands")
    goal_sub = goal.add_subparsers(dest="goal_command", required=True)
    goal_check = goal_sub.add_parser("check")
    goal_check.add_argument("--record", required=True)
    goal_check.add_argument("--state")
    goal_check.add_argument("--current", action="store_true")
    goal_summarize = goal_sub.add_parser("summarize")
    goal_summarize.add_argument("--record", required=True)
    goal_summarize.add_argument("--state", required=True)
    goal_summarize.add_argument("--profile")
    goal_summarize.add_argument("--target-window")
    goal_view = goal_sub.add_parser("view")
    goal_view.add_argument("--record", required=True)
    goal_view.add_argument("--state", required=True)
    goal_view.add_argument("--usage-receipt", action="append", default=[])
    goal_view.add_argument("--change-summary")
    goal_view.add_argument("--allow-stale-goal", action="store_true")
    goal_view.add_argument("--terminal", action="store_true")
    goal_view.add_argument("--out")
    goal_update = goal_sub.add_parser("update")
    goal_update.add_argument("--record", required=True)
    goal_update.add_argument("--state", required=True)
    goal_update.add_argument("--reason", required=True)
    goal_update.add_argument("--status", choices=["ACTIVE", "BLOCKED", "READY_FOR_FINALIZATION", "COMPLETE"])
    goal_update.add_argument("--evidence-id", action="append", default=[])
    goal_update.add_argument("--out")


def _add_model_parser(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    model = subparsers.add_parser("model", help="model routing commands")
    model_sub = model.add_subparsers(dest="model_command", required=True)
    model_route = model_sub.add_parser("route")
    model_route.add_argument("--request", required=True)
    model_route.add_argument("--profile", default="profiles/model-routing-profile.v1.json")
    model_route.add_argument("--host-profile")
    model_profile_check = model_sub.add_parser("profile-check")
    model_profile_check.add_argument("--profile", required=True)
    model_profile_check.add_argument("--type", choices=["auto", "routing", "host"], default="auto")
    model_usage_check = model_sub.add_parser("usage-check")
    model_usage_check.add_argument("--receipt", required=True)
    model_usage_check.add_argument("--route-decision")
    model_usage_check.add_argument("--budget-targets")


def _add_runner_parser(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    runner = subparsers.add_parser("runner", help="controlled execution-loop commands")
    runner_sub = runner.add_subparsers(dest="runner_command", required=True)
    runner_start = runner_sub.add_parser("start")
    runner_start.add_argument("--state", required=True)
    runner_start.add_argument("--runner", required=True)
    runner_start.add_argument("--policy")
    runner_start.add_argument("--operation-id", required=True)
    runner_start.add_argument("--reason", required=True)
    runner_status = runner_sub.add_parser("status")
    runner_status.add_argument("--runner", required=True)
    runner_status.add_argument("--state")
    runner_status.add_argument("--profile")
    runner_status.add_argument("--target-window")
    runner_transition = runner_sub.add_parser("transition")
    runner_transition.add_argument("--runner", required=True)
    runner_transition.add_argument("--state", required=True)
    runner_transition.add_argument("--request", required=True)
    runner_stop = runner_sub.add_parser("stop")
    runner_stop.add_argument("--runner", required=True)
    runner_stop.add_argument("--state", required=True)
    runner_stop.add_argument("--operation-id", required=True)
    runner_stop.add_argument("--expected-runner-revision", required=True, type=int)
    runner_stop.add_argument("--reason", required=True)
    runner_resume = runner_sub.add_parser("resume")
    runner_resume.add_argument("--runner", required=True)
    runner_resume.add_argument("--state", required=True)
    runner_resume.add_argument("--operation-id", required=True)
    runner_resume.add_argument("--expected-runner-revision", required=True, type=int)
    runner_resume.add_argument("--reason", required=True)


def _add_tier_parser(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    tier = subparsers.add_parser("tier", help="SDD tier commands")
    tier_sub = tier.add_subparsers(dest="tier_command", required=True)
    tier_resolve = tier_sub.add_parser("resolve")
    tier_resolve.add_argument("--request", required=True)


def _add_specification_parser(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    specification = subparsers.add_parser("specification", help="specification commands")
    specification_sub = specification.add_subparsers(dest="specification_command", required=True)
    specification_check = specification_sub.add_parser("check")
    specification_check.add_argument("--specification", required=True)
    completion_gate = specification_sub.add_parser("completion-gate")
    completion_gate.add_argument("--state", required=True)
    completion_gate.add_argument("--final-audit")
    completion_gate.add_argument("--follow-up-register")
    completion_gate.add_argument("--input")
    completion_gate.add_argument("--verifier", default="completion-gate")
    completion_gate.add_argument("--out")
